/*
Copyright Joyent, Inc. and other Node contributors.
Copyright 2011 uxebu Consulting Ltd. & Co. KG
Copyright 2011 David Aurelio <aurelio@uxebu.com>
Copyright 2011 Jens Arps <arps@uxebu.com>
Copyright 2011 Tobias Reiss <reiss@uxebu.com>
Copyright 2011 James Padolsey <padolsey@uxebu.com>
Copyright 2011 Stephan Seidt <seidt@uxebu.com>

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to permit
persons to whom the Software is furnished to do so, subject to the
following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
/*
 RequireJS 0.24.0 Copyright (c) 2010-2011, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
*/
var require,define;
(function(){function a(a){return"[object Function]"===u.call(a)}function g(a){return"[object Array]"===u.call(a)}function e(a,c,b){for(var f in c)if(!(f in N)&&(!(f in a)||b))a[f]=c[f];return j}function c(a,c,b){var f,h,d;for(f=0;d=c[f];f++){d="string"===typeof d?{name:d}:d;h=d.location;if(b&&(!h||0!==h.indexOf("/")&&-1===h.indexOf(":")))h=b+"/"+(h||d.name);a[d.name]={name:d.name,location:h||d.name,lib:d.lib||"lib",main:(d.main||"lib/main").replace(k,"").replace(n,"")}}}function b(b){function d(a){var b,c;
for(b=0;c=a[b];b++)if("."===c)a.splice(b,1),b-=1;else if(".."===c)if(1===b&&(".."===a[2]||".."===a[0]))break;else 0<b&&(a.splice(b-1,2),b-=2)}function f(a,b){var c,h;"."===a.charAt(0)&&b&&(F.pkgs[b]?b=[b]:(b=b.split("/"),b=b.slice(0,b.length-1)),a=b.concat(a.split("/")),d(a),h=F.pkgs[c=a[0]],a=a.join("/"),h&&a===c+"/"+h.main&&(a=c));return a}function i(a,b){var c=a?a.indexOf("!"):-1,d=null,h=b?b.name:null,e=a,k,g;-1!==c&&(d=a.substring(0,c),a=a.substring(c+1,a.length));d&&(d=f(d,h));a&&(k=d?(c=z[d])?
c.normalize?c.normalize(a,function(a){return f(a,h)}):f(a,h):"__$p"+h+"@"+a:f(a,h),g=K[k],g||(g=j.toModuleUrl?j.toModuleUrl(l,a,b):l.nameToUrl(a,null,b),K[k]=g));return{prefix:d,name:k,parentMap:b,url:g,originalName:e,fullName:d?d+"!"+k:k}}function k(){var a=!0,b=F.priorityWait,c,d;if(b){for(d=0;c=b[d];d++)if(!H[c]){a=!1;break}a&&delete F.priorityWait}return a}function g(a){return function(b){a.exports=b}}function n(b,c,d){return function(){var h=[].concat(t.call(arguments,0)),f;if(d&&a(f=h[h.length-
1]))f.__requireJsBuild=!0;h.push(c);return b.apply(null,h)}}function S(a,b){var c=n(l.require,a,b);e(c,{nameToUrl:n(l.nameToUrl,a),toUrl:n(l.toUrl,a),isDefined:n(l.isDefined,a),ready:j.ready,isBrowser:j.isBrowser});if(j.paths)c.paths=j.paths;return c}function u(a){var b=a.prefix,c=a.fullName;B[c]||c in z||(b&&!R[b]&&(R[b]=void 0,(V[b]||(V[b]=[])).push(a),(I[b]||(I[b]=[])).push({onDep:function(a){if(a===b){var c,d,h,f,e,k,g=V[b];if(g)for(h=0;c=g[h];h++)if(a=c.fullName,c=i(c.originalName,c.parentMap),
c=c.fullName,d=I[a]||[],f=I[c],c!==a){a in B&&(delete B[a],B[c]=!0);I[c]=f?f.concat(d):d;delete I[a];for(f=0;f<d.length;f++){k=d[f].depArray;for(e=0;e<k.length;e++)k[e]===a&&(k[e]=c)}}delete V[b]}}}),u(i(b))),l.paused.push(a))}function q(b){var c,d,f;c=b.callback;var h=b.fullName;f=[];var e=b.depArray;if(c&&a(c)){if(e)for(c=0;c<e.length;c++)f.push(b.deps[e[c]]);d=j.execCb(h,b.callback,f);if(h)if(b.usingExports&&void 0===d&&(!b.cjsModule||!("exports"in b.cjsModule)))d=z[h];else if(b.cjsModule&&"exports"in
b.cjsModule)d=z[h]=b.cjsModule.exports;else{if(h in z&&!b.usingExports)return j.onError(Error(h+" has already been defined"));z[h]=d}}else h&&(d=z[h]=c);if(h&&(f=I[h])){for(c=0;c<f.length;c++)f[c].onDep(h,d);delete I[h]}if(D[b.waitId])delete D[b.waitId],b.isDone=!0,l.waitCount-=1,0===l.waitCount&&(W=[])}function P(a,b,c,d){var a=i(a,d),h=a.name,f=a.fullName,e={},k={waitId:h||w+X++,depCount:0,depMax:0,prefix:a.prefix,name:h,fullName:f,deps:{},depArray:b,callback:c,onDep:function(a,b){a in k.deps||
(k.deps[a]=b,k.depCount+=1,k.depCount===k.depMax&&q(k))}},n,E;if(f){if(f in z||!0===H[f])return;B[f]=!0;H[f]=!0;l.jQueryDef="jquery"===f}for(c=0;c<b.length;c++)if(n=b[c])n=i(n,h?a:d),E=n.fullName,b[c]=E,"require"===E?k.deps[E]=S(a):"exports"===E?(k.deps[E]=z[f]={},k.usingExports=!0):"module"===E?(k.cjsModule=n=k.deps[E]={id:h,uri:h?l.nameToUrl(h,null,d):void 0},n.setExports=g(n)):E in z&&!(E in D)?k.deps[E]=z[E]:e[E]||(k.depMax+=1,u(n),(I[E]||(I[E]=[])).push(k),e[E]=!0);k.depCount===k.depMax?q(k):
(D[k.waitId]=k,W.push(k),l.waitCount+=1)}function Q(a){P.apply(null,a);H[a[0]]=!0}function r(a){if(!l.jQuery&&(a=a||("undefined"!==typeof jQuery?jQuery:null))&&"readyWait"in a)if(l.jQuery=a,Q(["jquery",[],function(){return jQuery}]),l.scriptCount)a.readyWait+=1,l.jQueryIncremented=!0}function v(a,b){if(!a.isDone){var c=a.fullName,h=a.depArray,d,f;if(c){if(b[c])return z[c];b[c]=!0}for(f=0;f<h.length;f++)if((d=h[f])&&!a.deps[d]&&D[d])a.onDep(d,v(D[d],b));return c?z[c]:void 0}}function C(){var a=1E3*
F.waitSeconds,b=a&&l.startTime+a<(new Date).getTime(),a="",c=!1,d=!1,f;if(!(0<l.pausedCount)){if(F.priorityWait)if(k())A();else return;for(f in H)if(!(f in N)&&(c=!0,!H[f]))if(b)a+=f+" ";else{d=!0;break}if(c||l.waitCount){if(b&&a)return f=Error("require.js load timeout for modules: "+a),f.requireType="timeout",f.requireModules=a,j.onError(f);if(d||l.scriptCount)(m||o)&&setTimeout(C,50);else if(l.waitCount){for(h=0;a=W[h];h++)v(a,{});C()}else j.checkReadyState()}}}function J(a,b){var c=b.name,f=b.fullName,
d;if(!(f in z||f in H))R[a]||(R[a]=z[a]),H[f]||(H[f]=!1),d=function(d){if(require.onPluginLoad)require.onPluginLoad(l,a,c,d);q({prefix:b.prefix,name:b.name,fullName:b.fullName,callback:function(){return d}});H[f]=!0},d.fromText=function(a,b){var c=L;l.loaded[a]=!1;l.scriptCount+=1;c&&(L=!1);eval(b);c&&(L=!0);l.completeLoad(a)},R[a].load(c,S(b.parentMap,!0),d,F)}function M(a){a.prefix&&0===a.name.indexOf("__$p")&&z[a.prefix]&&(a=i(a.originalName,a.parentMap));var b=a.prefix,c=a.fullName;!B[c]&&!H[c]&&
(B[c]=!0,b?z[b]?J(b,a):(T[b]||(T[b]=[],(I[b]||(I[b]=[])).push({onDep:function(a){if(a===b){for(var c,f=T[b],a=0;a<f.length;a++)c=f[a],J(b,i(c.originalName,c.parentMap));delete T[b]}}})),T[b].push(a)):j.load(l,c,a.url))}var l,A,F={waitSeconds:7,baseUrl:s.baseUrl||"./",paths:{},pkgs:{}},G=[],B={require:!0,exports:!0,module:!0},K={},z={},H={},D={},W=[],X=0,I={},R={},T={},U=0,V={};A=function(){var a,b,c;U+=1;if(0>=l.scriptCount)l.scriptCount=0;for(;G.length;){a=G.shift();if(null===a[0])return j.onError(Error("Mismatched anonymous require.def modules"));
Q(a)}if(!F.priorityWait||k())for(;l.paused.length;){c=l.paused;l.pausedCount+=c.length;l.paused=[];for(b=0;a=c[b];b++)M(a);l.startTime=(new Date).getTime();l.pausedCount-=c.length}1===U&&C();U-=1};l={contextName:b,config:F,defQueue:G,waiting:D,waitCount:0,specified:B,loaded:H,urlMap:K,scriptCount:0,urlFetched:{},defined:z,paused:[],pausedCount:0,plugins:R,managerCallbacks:I,makeModuleMap:i,normalize:f,configure:function(a){var b,f,d;a.baseUrl&&"/"!==a.baseUrl.charAt(a.baseUrl.length-1)&&(a.baseUrl+=
"/");b=F.paths;d=F.pkgs;e(F,a,!0);if(a.paths){for(f in a.paths)f in N||(b[f]=a.paths[f]);F.paths=b}if((b=a.packagePaths)||a.packages){if(b)for(f in b)f in N||c(d,b[f],f);a.packages&&c(d,a.packages);F.pkgs=d}if(a.priority)f=l.requireWait,l.requireWait=!1,l.takeGlobalQueue(),A(),l.require(a.priority),A(),l.requireWait=f,F.priorityWait=a.priority;if(a.deps||a.callback)l.require(a.deps||[],a.callback);a.ready&&j.ready(a.ready)},isDefined:function(a,b){return i(a,b).fullName in z},require:function(a,c,
f){if("string"===typeof a){if(j.get)return j.get(l,a,c);c=i(a,c);a=z[c.fullName];return void 0===a?j.onError(Error("require: module name '"+c.fullName+"' has not been loaded yet for context: "+b)):a}P(null,a,c,f);if(!l.requireWait)for(;!l.scriptCount&&l.paused.length;)A()},takeGlobalQueue:function(){O.length&&(p.apply(l.defQueue,[l.defQueue.length-1,0].concat(O)),O=[])},completeLoad:function(a){var b;for(l.takeGlobalQueue();G.length;)if(b=G.shift(),null===b[0]){b[0]=a;break}else if(b[0]===a)break;
else Q(b),b=null;b?Q(b):Q([a,[],"jquery"===a&&"undefined"!==typeof jQuery?function(){return jQuery}:null]);H[a]=!0;r();j.isAsync&&(l.scriptCount-=1);A();j.isAsync||(l.scriptCount-=1)},toUrl:function(a,b){var c=a.lastIndexOf("."),f=null;-1!==c&&(f=a.substring(c,a.length),a=a.substring(0,c));return l.nameToUrl(a,f,b)},nameToUrl:function(a,b,c){var h,k,e,i,g=l.config;if(0===a.indexOf("./")||0===a.indexOf("../"))c=c&&c.url?c.url.split("/"):[],c.length&&c.pop(),c=c.concat(a.split("/")),d(c),b=c.join("/")+
(b?b:j.jsExtRegExp.test(a)?"":".js");else if(a=f(a,c),j.jsExtRegExp.test(a))b=a+(b?b:"");else{h=g.paths;k=g.pkgs;c=a.split("/");for(i=c.length;0<i;i--)if(e=c.slice(0,i).join("/"),h[e]){c.splice(0,i,h[e]);break}else if(e=k[e]){a=a===e.name?e.location+"/"+e.main:e.location+"/"+e.lib;c.splice(0,i,a);break}b=c.join("/")+(b||".js");b=("/"===b.charAt(0)||b.match(/^\w+:/)?"":g.baseUrl)+b}return g.urlArgs?b+((-1===b.indexOf("?")?"?":"&")+g.urlArgs):b}};l.jQueryCheck=r;l.resume=A;return l}function d(){var a,
b,c;if(G&&"interactive"===G.readyState)return G;a=document.getElementsByTagName("script");for(b=a.length-1;-1<b&&(c=a[b]);b--)if("interactive"===c.readyState)return G=c;return null}var i=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,f=/require\(["']([^'"\s]+)["']\)/g,k=/^\.\//,n=/\.js$/,u=Object.prototype.toString,q=Array.prototype,t=q.slice,p=q.splice,m=!!("undefined"!==typeof window&&navigator&&document),o=!m&&"undefined"!==typeof importScripts,r=m&&"PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/,
v="undefined"!==typeof opera&&"[object Opera]"===opera.toString(),w="_r@@",N={},J={},O=[],G=null,L=!1,j,q={},M,s,A,B,C,K,D,h,S,Q,P;if("undefined"!==typeof require){if(a(require))return;q=require}j=require=function(a,c,f){var d="_",h;!g(a)&&"string"!==typeof a&&(h=a,g(c)?(a=c,c=f):a=[]);if(h&&h.context)d=h.context;f=J[d]||(J[d]=b(d));h&&f.configure(h);return f.require(a,c)};j.version="0.24.0";j.isArray=g;j.isFunction=a;j.mixin=e;j.jsExtRegExp=/^\/|:|\?|\.js$/;s=j.s={contexts:J,skipAsync:{},isPageLoaded:!m,
readyCalls:[]};if(j.isAsync=j.isBrowser=m)if(A=s.head=document.getElementsByTagName("head")[0],B=document.getElementsByTagName("base")[0])A=s.head=B.parentNode;j.onError=function(a){throw a;};j.load=function(a,b,c){var f=a.contextName,d=a.urlFetched,h=a.loaded;h[b]||(h[b]=!1);if(!d[c]&&(a.scriptCount+=1,j.attach(c,f,b),d[c]=!0,a.jQuery&&!a.jQueryIncremented))a.jQuery.readyWait+=1,a.jQueryIncremented=!0};define=j.def=function(a,b,c){var h;"string"!==typeof a&&(c=b,b=a,a=null);j.isArray(b)||(c=b,b=
[]);!a&&!b.length&&j.isFunction(c)&&c.length&&(c.toString().replace(i,"").replace(f,function(a,c){b.push(c)}),b=["require","exports","module"].concat(b));if(L){h=M||d();if(!h)return j.onError(Error("ERROR: No matching script interactive for "+c));a||(a=h.getAttribute("data-requiremodule"));h=J[h.getAttribute("data-requirecontext")]}(h?h.defQueue:O).push([a,b,c])};define.amd={multiversion:!0,plugins:!0};j.execCb=function(a,b,c){return b.apply(null,c)};j.onScriptLoad=function(a){var b=a.currentTarget||
a.srcElement,c;if("load"===a.type||r.test(b.readyState))G=null,a=b.getAttribute("data-requirecontext"),c=b.getAttribute("data-requiremodule"),J[a].completeLoad(c),b.detachEvent&&!v?b.detachEvent("onreadystatechange",j.onScriptLoad):b.removeEventListener("load",j.onScriptLoad,!1)};j.attach=function(a,b,c,f,d){var h;if(m)return f=f||j.onScriptLoad,h=document.createElement("script"),h.type=d||"text/javascript",h.charset="utf-8",h.async=!s.skipAsync[a],h.setAttribute("data-requirecontext",b),h.setAttribute("data-requiremodule",
c),h.attachEvent&&!v?(L=!0,h.attachEvent("onreadystatechange",f)):h.addEventListener("load",f,!1),h.src=a,M=h,B?A.insertBefore(h,B):A.appendChild(h),M=null,h;if(o)f=J[b],b=f.loaded,b[c]=!1,importScripts(a),f.completeLoad(c);return null};if(m){C=document.getElementsByTagName("script");for(h=C.length-1;-1<h&&(K=C[h]);h--){if(!A)A=K.parentNode;if(D=K.getAttribute("data-main")){if(!q.baseUrl)C=D.split("/"),K=C.pop(),C=C.length?C.join("/")+"/":"./",q.baseUrl=C,D=K.replace(n,"");q.deps=q.deps?q.deps.concat(D):
[D];break}}}s.baseUrl=q.baseUrl;j.pageLoaded=function(){if(!s.isPageLoaded){s.isPageLoaded=!0;S&&clearInterval(S);if(Q)document.readyState="complete";j.callReady()}};j.checkReadyState=function(){var a=s.contexts,b;for(b in a)if(!(b in N)&&a[b].waitCount)return;s.isDone=!0;j.callReady()};j.callReady=function(){var a=s.readyCalls,b,c,f;if(s.isPageLoaded&&s.isDone){if(a.length){s.readyCalls=[];for(b=0;c=a[b];b++)c()}a=s.contexts;for(f in a)if(!(f in N)&&(b=a[f],b.jQueryIncremented))b.jQuery.ready(!0),
b.jQueryIncremented=!1}};j.ready=function(a){s.isPageLoaded&&s.isDone?a():s.readyCalls.push(a);return j};if(m){if(document.addEventListener){if(document.addEventListener("DOMContentLoaded",j.pageLoaded,!1),window.addEventListener("load",j.pageLoaded,!1),!document.readyState)Q=!0,document.readyState="loading"}else window.attachEvent&&(window.attachEvent("onload",j.pageLoaded),self===self.top&&(S=setInterval(function(){try{document.body&&(document.documentElement.doScroll("left"),j.pageLoaded())}catch(a){}},
30)));"complete"===document.readyState&&j.pageLoaded()}j(q);if(j.isAsync&&"undefined"!==typeof setTimeout)P=s.contexts[q.context||"_"],P.requireWait=!0,setTimeout(function(){P.requireWait=!1;P.takeGlobalQueue();P.jQueryCheck();P.scriptCount||P.resume();j.checkReadyState()},0)})();define("requireLib",function(){});
define("event_emitter",[],function(){var a;a={addListener:function(a,e){if("function"!==typeof e)throw Error("addListener only takes instances of Function");var c=this._events||(this._events=Object.create(null)),b=c[a],d,i;if(b){i=e.listener||e;for(c=0;d=b[c];c++)if(i===d||i===d.listener)return this;b.push(e)}else c[a]=[e];return this},emit:function(a,e,c){var b,d,i,f;i=this._events;if("error"===a&&(!i||!i.error||!i.error.length)){if(e instanceof Error)throw e;throw Error("Uncaught, unspecified \u201cerror\u201d event.");
}if(!i)return!1;if(i=i[a]){i=i.slice();d=arguments.length;switch(d){case 1:break;case 2:b=[e];break;case 3:b=[e,c];break;default:b=[];for(f=1;f<d;f++)b[f-1]=arguments[f]}for(f=0;d=i[f];f++)d.apply(this,b)}return this},listeners:function(a){var e=this._events||(this._events=Object.create(null));return e[a]||(e[a]=[])},once:function(a,e){if("function"!==typeof e)throw Error("once only takes instances of Function");var c=function(){this.removeListener(a,c);e.apply(this,arguments)};c.listener=e;return this.on(a,
c)},removeAllListeners:function(a){var e=this._events;0===arguments.length?delete this._events:e&&delete e[a];return this},removeListener:function(a,e){if("function"!==typeof e)throw Error("removeListener only takes instances of Function");var c,b,d=(c=this._events)&&c[a];if(c&&d)for(c=0;b=d[c];c++)if(e===b||e===b.listener){d.splice(c,1);break}return this}};a.on=a.addListener;return a});
define("color_map",{aliceblue:4042850303,antiquewhite:4209760255,aqua:16777215,aquamarine:2147472639,azure:4043309055,beige:4126530815,bisque:4293182719,black:255,blanchedalmond:4293643775,blue:65535,blueviolet:2318131967,brown:2771004159,burlywood:3736635391,cadetblue:1604231423,chartreuse:2147418367,chocolate:3530104575,coral:4286533887,cornflowerblue:1687547391,cornsilk:4294499583,crimson:3692313855,cyan:16777215,darkblue:35839,darkcyan:9145343,darkgoldenrod:3095792639,darkgray:2846468607,darkgreen:6553855,
darkgrey:2846468607,darkkhaki:3182914559,darkmagenta:2332068863,darkolivegreen:1433087999,darkorange:4287365375,darkorchid:2570243327,darkred:2332033279,darksalmon:3918953215,darkseagreen:2411499519,darkslateblue:1211993087,darkslategray:793726975,darkslategrey:793726975,darkturquoise:13554175,darkviolet:2483082239,deeppink:4279538687,deepskyblue:12582911,dimgray:1768516095,dimgrey:1768516095,dodgerblue:512819199,firebrick:2988581631,floralwhite:4294635775,forestgreen:579543807,fuchsia:4278255615,
gainsboro:3705462015,ghostwhite:4177068031,gold:4292280575,goldenrod:3668254975,gray:2155905279,green:8388863,greenyellow:2919182335,grey:2155905279,honeydew:4043305215,hotpink:4285117695,indianred:3445382399,indigo:1258324735,ivory:4294963455,khaki:4041641215,lavender:3873897215,lavenderblush:4293981695,lawngreen:2096890111,lemonchiffon:4294626815,lightblue:2916673279,lightcoral:4034953471,lightcyan:3774873599,lightgoldenrodyellow:4210742015,lightgray:3553874943,lightgreen:2431553791,lightgrey:3553874943,
lightpink:4290167295,lightsalmon:4288707327,lightseagreen:548580095,lightskyblue:2278488831,lightslategray:2005441023,lightslategrey:2005441023,lightsteelblue:2965692159,lightyellow:4294959359,lime:16711935,limegreen:852308735,linen:4210091775,magenta:4278255615,maroon:2147483903,mediumaquamarine:1724754687,mediumblue:52735,mediumorchid:3126187007,mediumpurple:2473647103,mediumseagreen:1018393087,mediumslateblue:2070474495,mediumspringgreen:16423679,mediumturquoise:1221709055,mediumvioletred:3340076543,
midnightblue:421097727,mintcream:4127193855,mistyrose:4293190143,moccasin:4293178879,navajowhite:4292783615,navy:33023,oldlace:4260751103,olive:2155872511,olivedrab:1804477439,orange:4289003775,orangered:4282712319,orchid:3664828159,palegoldenrod:4008225535,palegreen:2566625535,paleturquoise:2951671551,palevioletred:3681588223,papayawhip:4293907967,peachpuff:4292524543,peru:3448061951,pink:4290825215,plum:3718307327,powderblue:2967529215,purple:2147516671,red:4278190335,rosybrown:3163525119,royalblue:1097458175,
saddlebrown:2336560127,salmon:4202722047,sandybrown:4104413439,seagreen:780883967,seashell:4294307583,sienna:2689740287,silver:3233857791,skyblue:2278484991,slateblue:1784335871,slategray:1887473919,slategrey:1887473919,snow:4294638335,springgreen:16744447,steelblue:1182971135,tan:3535047935,teal:8421631,thistle:3636451583,tomato:4284696575,transparent:0,turquoise:1088475391,violet:4001558271,wheat:4125012991,white:4294967295,whitesmoke:4126537215,yellow:4294902015,yellowgreen:2597139199});
define("tools",["color_map"],function(a){function g(a,c,b){b=0>b?b+1:1<b?b-1:b;return 1>6*b?a+6*(c-a)*b:1>2*b?c:2>3*b?a+6*(c-a)*(2/3-b):a}return{descriptorAccessor:function(a,c,b,d){return{get:a,set:c,enumerable:!!b,configurable:!!d}},descriptorData:function(a,c,b,d){return{value:a,writable:!!c,enumerable:!!b,configurable:!!d}},getter:function(a){return function(){return this[a]}},mixin:function(a,c){var b,d,i,f,k=2,n=Object.keys;do if(c){f=n(c);for(b=0,d=f.length;b<d;b++)i=f[b],a[i]=c[i]}while(c=
arguments[k++]);return a},parseColor:function(e,c){var b,d;if(+e)return e>>>0;if(e in a)return a[e];if(/^#[0-9a-f]{6}$/i.test(e))return(parseInt(e.slice(1),16)<<8|255)>>>0;if(/^#[0-9a-f]{3}$/i.test(e)){e=parseInt(e.slice(1),16);d=e&3840;b=e&240;var i=e&15;return(d<<20|d<<16|b<<16|b<<12|i<<12|i<<8|255)>>>0}e=(""+e).split("(");if(2===e.length)switch(e[0]){case "rgb":b=/\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)$/,d=255;case "rgba":b||(b=/\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(0|1|[01]?(?:\.\d+))\s*\)$/);
if(b=b.exec(e[1]))return((b[1]&255)<<24|(b[2]&255)<<16|(b[3]&255)<<8|(d||255*b[4]&255))>>>0;break;case "hsl":b=/\s*(\d+)\s*,\s*(\d+)%\s*,\s*(\d+)%\s*\)$/,d=255;case "hsla":if(b||(b=/\s*(\d+)\s*,\s*(\d+)%\s*,\s*(\d+)%\s*,\s*(0|1|[01]?(?:\.\d+))\s*\)$/),b=b.exec(e[1])){var i=b[1]%360/360,f=b[2]/100,k=b[3]/100,f=0.5>=k?k*(f+1):k+f-k*f,n=2*k-f,k=255*g(n,f,i+1/3),u=255*g(n,f,i),i=255*g(n,f,i-1/3);return((k+0.5<<16)+(u+0.5<<8)+(i+0.5|0)<<8|(d||255*b[4]&255))>>>0}}return null===c||void 0===c?255:c},hitch:function(a,
c){c||(c=a,a=null);if("string"===typeof c){a=a||window;if(!a[c])throw["method not found"];return function(){return a[c].apply(a,arguments||[])}}return!a?c:function(){return c.apply(a,arguments||[])}},toArray:function(a,c,b){return(b||[]).concat(Array.prototype.slice.call(a,c||0))}}});
define("timeline",["event_emitter","tools"],function(a,g){var e=Math.round;return g.mixin({currentFrame:0,isPlaying:!0,advance:function(){var a=this.currentFrame;this.emit("tick",this,a);if(this.isPlaying)this.emit("advance",this,a),this.emit(a,this,a),this.currentFrame=(a+1)%this.length()||0},frames:function(a){var b,d,i=0;for(d in a)b=+d,b!=d&&(b=this.toFrameNumber(d)),b>i&&(i=b),this.on(b,a[d]);if(i>this.length())this._length=i+1;return this},length:function(a){var b=this._length||(this._length=
0);if(0===arguments.length)return b;for(a*=1;b-- >=a;)this.removeAllListeners(b);this._length=a;return this},play:function(a){a*=1;this.isPlaying=!0;if(0<=a&&a<this.length())this.currentFrame=a,this.emit(a,this,a);return this},stop:function(a){a*=1;this.isPlaying=!1;if(0<=a&&a<this.length())this.currentFrame=a,this.emit(a,this,a);return this},toFrameNumber:function(a){if(a==+a)return+a;a=(""+a).split(/([^\d.]+)/);switch(a[1]){case "ms":a[0]/=1E3;case "s":return e(a[0]*(this.framerate||bikeshed.stage.framerate));
case "%":return e(this._length*a[0]/100)||0;default:throw Error("Unknown frame format: "+a[1]);}}},a)});define("registry",[],function(){return{displayObjects:Object.create(null),loadingDisplayObjects:Object.create(null),movies:Object.create(null),needsDraw:Object.create(null)}});
define("display_list",["./registry"],function(a){var g;g={isVisible:!1,addChild:function(e,c){e.parent=this;e.isVisible=this.isVisible;a.displayObjects[e.id]=e;"function"===typeof e.advance&&(a.movies[e.id]=e);"undefined"!==typeof c?this._children.splice(c,0,e):this._children.push(e);this.isVisible&&e.markUpdate();return e},children:function(a){if(!a)return this._children.slice(0);a.forEach(function(a){this.add(a)},this);return this},clear:function(){this._children.slice(0).map(this.remove,this);
return this},getIndexOfChild:function(a){return this._children.indexOf(a)},removeChild:function(e){var c=this._children,b=c.indexOf(e);-1!==b&&(delete a.displayObjects[e.id],delete a.movies[e.id],delete a.needsDraw[e.id],c.splice(b,1));return this}};g.add=g.addChild;return g});
define("stage",["./event_emitter","./display_list","./timeline","./tools","./registry"],function(a,g,e,c,b){var d=b.movies,i={init:function(a){this.options=a;a=Math.abs(a.framerate|0)||30;setInterval(i.loop,1E3/a);Object.defineProperty(this,"framerate",{value:a})},handleEvent:function(a){if("message"===a.type){var c=a.data,a=c.command,c=c.data;switch(a){case "play":case "stop":this[a](c);break;case "assetLoaded":if(c.id in b.loadingDisplayObjects)b.loadingDisplayObjects[c.id].emit("assetLoaded",c);
else throw Error("Couldn't fine id: "+c.id+" in `loadingDisplayObjects`");break;case "userevent":b.displayObjects[c.id].emit(c.type,c.args)}}},loop:function(){i.advance();for(var a in d)d[a].advance();var k=[],e;for(e in b.needsDraw){delete b.needsDraw[e];var g=b.displayObjects[e];a={id:e};if(g){if(!g.composeRenderMessage)continue;c.mixin(a,g.composeRenderMessage())}k.push(a)}k.length&&postMessage({command:"render",data:k,frame:i.currentFrame})}};Object.defineProperty(i,"id",{value:0});c.mixin(i,
a,g,e);i.isVisible=!0;i._children=[];return i});
define("point",[],function(){var a,g=Math.sqrt;a=function(a,b){this.x=a||0;this.y=b||0};var e=a.prototype;e.add=function(a){this.x+=a.x;this.y+=a.y;return this};e.equals=function(a){return this.x===a.x&&this.y===a.y};e.clone=function(){return new a(this.x,this.y)};e.normalize=function(a){g(this.x*this.x+this.y*this.y);a/=this.length;this.x*=a;this.y*=a;return this};e.offset=function(a,b){this.x+=a;this.y+=b;return this};e.subtract=function(a){this.x-=a.x;this.y-=a.y;return this};e.toString=function(){return this.x+
","+this.y+" "};e.toObject=function(){return Object.create(null,{x:{value:this.x},y:{value:this.y}})};e.toArray=function(){return[this.x,this.y]};e.distance=function(a){var b=this.x-a.x,a=this.y-a.y;return g(b*b+a*a)};a.interpolate=function(c,b,d){return new a(c.x+d*(c.x-b.x),c.y+d*(c.y-b.y))};a.polar=function(c,b){return new a(c*Math.cos(b),c*Math.sin(b))};return a});
define("error",[],function(){function a(a){this.name="ParserError";this.message=a[0]}a.prototype=Error();a.prototype.constructor=a;return{ParserError:a}});
define("segment_helper",["./point","./error"],function(a,g){function e(a,b){var f=[],d=!0,i=[],e,m,o,r,v,w,b=b||c;for(r=0,v=a.length;r<v;r++)if(o=a[r],d){f=[];if(!b[o])throw new g.ParserError(['Unknown command: "'+o+'"']);f.push(o);e=o;m=b[o].attributes.slice(0);(d=!m.length)&&i.push(f)}else{w=m.shift();switch(w){case "B":f.push(!!o);break;case "N":w=parseFloat(o,10);if(isNaN(w))throw new g.ParserError(['Invalid parameter for command "'+e+'", expected numeric but got "'+o+'".']);f.push(w);break;case "P":w=
parseFloat(o,10);if(isNaN(w))throw new g.ParserError(['Could not create Point from String                 for command "'+e+'", expected numeric but got                 "'+o+'".']);f.push(w);w=parseFloat(a[++r],10);if(isNaN(w))throw new g.ParserError(['Could not create Point from String                  for command "'+e+'", expected numeric but got                  "'+a[r]+'".']);f.push(w)}m.length||(d=!0,i.push(f))}return i}var c={moveTo:{attributes:["P"],shorthands:["M"]},moveBy:{attributes:["P"],
shorthands:["m"]},closePath:{attributes:[],shorthands:["Z","z"]},lineTo:{attributes:["P"],shorthands:["L"]},lineBy:{attributes:["P"],shorthands:["l"]},verticalLineTo:{attributes:["N"],shorthands:["V"]},verticalLineBy:{attributes:["N"],shorthands:["v"]},horizontalLineTo:{attributes:["N"],shorthands:["H"]},horizontalLineBy:{attributes:["N"],shorthands:["h"]},arcTo:{attributes:["P","P","B","B","P"],shorthands:["A"]},arcBy:{attributes:["P","P","B","B","P"],shorthands:["a"]},curveTo:{attributes:["P","P",
"P"],shorthands:["C"]},curveBy:{attributes:["P","P","P"],shorthands:["c"]},throughCurveTo:{attributes:["P","P"],shorthands:["TC"]},throughCurveBy:{attributes:["P","P"],shorthands:["tc"]},quadraticCurveTo:{attributes:["P","P"],shorthands:["Q"]},quadraticCurveBy:{attributes:["P","P"],shorthands:["q"]},smoothCurveTo:{attributes:["P","P"],shorthands:["S"]},smoothCurveBy:{attributes:["P","P"],shorthands:["s"]},smoothQuadraticCurveTo:{attributes:["P"],shorthands:["T"]},smoothQuadraticCurveBy:{attributes:["P"],
shorthands:["t"]}},b=Object.create(null),d;for(d in c)c[d].shorthands.forEach(function(a){b[a]=d});var i=Object.create(null);for(d in c)i[d]=c[d].shorthands[0];var f=[];for(d in c)f.push(d),f=f.concat(c[d].shorthands);return{validTokens:f,parsePath:function(a){var c=[];a.replace(/([a-z])[\s,]*((-?\d*\.?\d*(?:e[\-+]?\d+)?\s*,?\s*)+)/ig,function(a,f,d){c.push(b[f]);d.replace(/(-?\d*\.?\d*(?:e[\-+]?\d+)?)\s*,?\s*/ig,function(a,b){b&&c.push(b)})});return e(c)},exportToPath:function(a){return a.map(function(a){return a.map(function(a){return"string"===
typeof a?i[a]:a}).join(" ")}).join(" ")},parseCommandList:e}});define("asset_loading",["./registry"],function(a){return{load:function(g,e){a.loadingDisplayObjects[this.id]=this;this.once("assetLoaded",function(){delete a.loadingDisplayObjects[this.id]});postMessage({command:"loadAsset",data:{type:e,id:this.id,source:g}});return this}}});
define("easing",{linear:function(a){return a},quadIn:function(a){return Math.pow(a,2)},quadOut:function(a){return-1*a*(a-2)},quadInOut:function(a){a*=2;return 1>a?Math.pow(a,2)/2:-1*(--a*(a-2)-1)/2},cubicIn:function(a){return Math.pow(a,3)},cubicOut:function(a){return Math.pow(a-1,3)+1},cubicInOut:function(a){a*=2;return 1>a?Math.pow(a,3)/2:(Math.pow(a-2,3)+2)/2},quartIn:function(a){return Math.pow(a,4)},quartOut:function(a){return-1*(Math.pow(a-1,4)-1)},quartInOut:function(a){a*=2;return 1>a?Math.pow(a,
4)/2:-0.5*(Math.pow(a-2,4)-2)},quintIn:function(a){return Math.pow(a,5)},quintOut:function(a){return Math.pow(a-1,5)+1},quintInOut:function(a){a*=2;return 1>a?Math.pow(a,5)/2:(Math.pow(a-2,5)+2)/2},sineIn:function(a){return-1*Math.cos(a*(Math.PI/2))+1},sineOut:function(a){return Math.sin(a*(Math.PI/2))},sineInOut:function(a){return-1*(Math.cos(Math.PI*a)-1)/2},expoIn:function(a){return 0===a?0:Math.pow(2,10*(a-1))},expoOut:function(a){return 1===a?1:-1*Math.pow(2,-10*a)+1},expoInOut:function(a){if(0===
a)return 0;if(1===a)return 1;a*=2;if(1>a)return Math.pow(2,10*(a-1))/2;--a;return(-1*Math.pow(2,-10*a)+2)/2},circIn:function(a){return-1*(Math.sqrt(1-Math.pow(a,2))-1)},circOut:function(a){return Math.sqrt(1-Math.pow(a-1,2))},circInOut:function(a){a*=2;return 1>a?-0.5*(Math.sqrt(1-Math.pow(a,2))-1):0.5*(Math.sqrt(1-Math.pow(a-2,2))+1)},backIn:function(a){return Math.pow(a,2)*(2.70158*a-1.70158)},backOut:function(a){a-=1;return Math.pow(a,2)*(2.70158*a+1.70158)+1},backInOut:function(a){a*=2;if(1>a)return Math.pow(a,
2)*(3.5949095*a-2.5949095)/2;a-=2;return(Math.pow(a,2)*(3.5949095*a+2.5949095)+2)/2},elasticIn:function(a){if(0===a||1===a)return a;a-=1;return-1*Math.pow(2,10*a)*Math.sin((a-0.075)*2*Math.PI/0.3)},elasticOut:function(a){return 0===a||1===a?a:Math.pow(2,-10*a)*Math.sin((a-0.075)*2*Math.PI/0.3)+1},elasticInOut:function(a){if(0===a)return 0;a*=2;if(2===a)return 1;var g=0.3*1.5,e=g/4;if(1>a)return a-=1,-0.5*Math.pow(2,10*a)*Math.sin((a-e)*2*Math.PI/g);a-=1;return 0.5*Math.pow(2,-10*a)*Math.sin((a-e)*
2*Math.PI/g)+1},bounceIn:function(a){return 1-easingFuncs.bounceOut(1-a)},bounceOut:function(a){return a=a<1/2.75?7.5625*Math.pow(a,2):a<2/2.75?7.5625*Math.pow(a-1.5/2.75,2)+0.75:a<2.5/2.75?7.5625*Math.pow(a-2.25/2.75,2)+0.9375:7.5625*Math.pow(a-2.625/2.75,2)+0.984375},bounceInOut:function(a){return 0.5>a?easingFuncs.bounceIn(2*a)/2:easingFuncs.bounceOut(2*a-1)/2+0.5}});
define("animation",["./easing","./timeline","./tools","./event_emitter"],function(a,g,e,c){function b(b,c,d){d||(d={});this._parseEventProps(d);var e=d.easing;this.easing=e instanceof Function?e:a[e];e=this.clock=d.clock||bikeshed.stage;b=this.duration=+b||e.toFrameNumber(b);this.repeat=d.repeat-(d.repeat%1||0);var g=this;"from"in d?(Object.defineProperty(this,"isTimelineBound",{value:!0}),this.from=+d.from||e.toFrameNumber(d.from),this.onStep=function(a,b){var c=g.from,d=g.duration,f=c+d;if(b>=c||
b<=f||b>=c||b<=f)c=(b-c)/d,g.step(1<c?1:0>c?0:c)},e.on("advance",this.onStep)):(this.frame=0,this.onStep=function(){var a=g.duration,b=++g.frame;g.step(b/a);b===a&&(g.reset(),0<g.repeat--&&g.play())},d.subject&&this.setSubject(d.subject,d.strategy));this.delay=d.delay||0;this.properties=c;this.propertyNames=Object.keys(c);this.startValues=0}var d=e.mixin;b.prototype={play:function(a,b){if(this.isTimelineBound)return this;a&&this.setSubject(a,b);if(!this.subject)throw Error("play() cannot run without a subject");
this.clock.on("tick",this.onStep);0===this.frame&&this.emit("beforebegin",this.subject,this);this.emit("play",this);this.isPlaying=!0;return this},pause:function(){if(this.isTimelineBound)return this;this.clock.removeListener("tick",this.onStep);this.emit("pause",this);this.isPlaying=!1},clone:function(){var a={clock:this.clock,duration:this.duration,easing:this.easing};if("from"in this)a.from=this.from;return new b(this.duration,d({},this.properties),a)},_parseEventProps:function(a){var b,c;for(b in a)0===
b.indexOf("on")&&(c=b.substring(2).toLowerCase(),this.on(c,a[b]),delete a[b])},reset:function(){if(this.isTimelineBound)return this;this.frame=0;this.isPlaying=!1;this.clock.removeListener("tick",this.onStep);return this},setSubject:function(a,b){this.strategy=b||(b="attr");this.subject=a;var c,d=this.propertyNames;switch(b){case "attr":c=a.attr();break;case "prop":c={};for(var e=0,g;g=d[e++];)c[g]=a[g];break;default:c=b.get(a,this.propertyNames)}this.initialValues=c;return this},step:function(a){var b,
c,d,e,g;b=this.easing;var t=this.properties,p=this.initialValues,m=this.propertyNames,o=this.strategy,r="prop"===o,v=this.subject,w={};b&&(a=b(a));for(c=0,e=m.length;c<e;c++)d=m[c],b=p[d],g=t[d],(r?v:w)[d]=b+(g-b)*a;"attr"===o?v.attr(w):r||o.set(v,w);1===a&&this.emit("end",this);return this}};d(b.prototype,c);return b});
define("keyframe_animation",["./animation","./easing","./tools","./event_emitter"],function(a,g,e,c){function b(a,b,c){c||(c={});var d=this.clock=c.clock||bikeshed.stage,a=this.duration=+a||d.toFrameNumber(a);this.animations=[];this.currentAnimation=-1;this.keyframes=this._convertKeysToFrames(b);this.keys=Object.keys(this.keyframes).map(Number);this.keys.sort(function(a,b){return a-b});this._fillInProperties();this._createAnimations();c.subject&&this.setSubject(c.subject,c.strategy)}var d={}.hasOwnProperty;
b.prototype={play:function(a,b){a&&this.setSubject(a,b);if(0>this.currentAnimation)this.begin();else return this.animations[this.currentAnimation].isPlaying=!0,this},pause:function(){if(-1<this.currentAnimation)this.animations[this.currentAnimation].isPlaying=!1;return this},reset:function(){this.animations.forEach(function(a){a.reset()});this.currentAnimation=-1;return this},begin:function(){var a=this.keyframes[0],b=this.subject,c=this.strategy;if(a&&b)switch(c){case "attr":b.attr(a);break;case "prop":for(var d in a)b[d]=
a[d];break;default:c.set(b,a)}this.currentAnimation=0;this.animations[0].play(b,c);return this},setSubject:function(a,b){this.strategy=b||"attr";this.subject=a;return this},_createAnimations:function(){var b,c=0,d,g=this.animations,u=this.keyframes;this.keys.forEach(function(q,t){var p;if(0!==q){b=q-c;c+=b;p=new a(b,u[q],{easing:this.easing,clock:this.clock,subject:this.subject,strategy:this.strategy});if(d)d.on("end",e.hitch(this,function(){this.currentAnimation++;p.play(this.subject,this.strategy)}));
g.push(p);d=p;if(t===this.keys.length-1)p.on("end",e.hitch(this,function(){this.emit("end")}))}},this)},_fillInProperties:function(){var a=this.duration,b=this.keys,c=this.keyframes,e,g={};b.forEach(function(a){e=c[a];for(var b in e)e.hasOwnProperty(b)&&(g[b]=!0)});b.forEach(function(q,t){var p,m,o,r,v;e=c[q];for(v in g)if(!d.call(e,v)){a:{p=v;for(m=t;m--;)if(d.call(c[b[m]],p)){p=b[m];break a}p=null}a:{m=v;o=t;for(r=b.length;o<r;++o)if(d.call(c[b[o]],m)){m=b[o];break a}m=null}o=p&&c[p][v];r=m&&c[m][v];
if(null===o||void 0===o)throw Error("No initial value specified for property: "+v);if(null===r||void 0===r)r=o,m=a;e[v]=r*(q-p)/(m-p)}})},_convertKeysToFrames:function(a){for(var b,c,d=0,e=this.clock,g=this.duration,t=Object.keys(a),p=Object.create(null),m=0,o=t.length;m<o;m++)b=t[m],c=b==+b?b:"from"===b?0:"to"===b?g:/^\d+%$/.test(b)?g*parseFloat(b)/100:e.toFrameNumber(b),p[c]=a[b],c>d&&(d=c);if(d>this.duration)this.duration=d;return p}};e.mixin(b.prototype,c);return b});
define("matrix",["point"],function(a){function g(a,c,e,f,g,n){this.a=null!==a&&void 0!==a?a:1;this.b=c||0;this.c=e||0;this.d=null!==f&&void 0!==f?f:1;this.tx=g||0;this.ty=n||0}var e=Math.cos,c=Math.sin;g.prototype={clone:function(){return new g(this.a,this.b,this.c,this.d,this.tx,this.ty)},concat:function(a){var c=this.a,e=this.b,f=this.c,g=this.d,n=this.tx,u=this.ty;this.a=c*a.a+e*a.c;this.b=c*a.b+e*a.d;this.c=f*a.a+g*a.c;this.d=f*a.b+g*a.d;this.tx=n*a.a+u*a.c+a.tx;this.ty=n*a.b+u*a.d+a.ty;return this},
createBox:function(a,c,e,f,g){return this.identify().rotate(e).scale(a,c).translate(f,g)},deltaTransformPoint:function(b){return new a(this.a*b.x+this.c*b.y,this.b*b.x+this.d*b.y)},identify:function(){this.a=this.d=1;this.b=this.c=this.tx=this.ty=0;return this},invert:function(){var a=this.a*this.d-this.b*this.c,c=this.a,e=this.b,f=this.c,g=this.d,n=this.tx,u=this.ty;this.a=g/a;this.b=-e/a;this.c=-f/a;this.d=c/a;this.tx=(f*u-g*n)/a;this.ty=(e*n-c*u)/a;return this},rotate:function(a){var d=e(a),a=
c(a);return this.concat(new g(d,a,-a,d,0,0))},scale:function(a,c){this.a*=a;this.b*=c;this.c*=a;this.d*=c;this.tx*=a;this.ty*=c;return this},transformPoint:function(b){return new a(this.a*b.x+this.c*b.y+this.tx,this.b*b.x+this.d*b.y+this.ty)},translate:function(a,c){this.tx+=a;this.ty+=c;return this}};return g});
define("display_object","./event_emitter,./tools,./registry,./matrix,./point,./animation,./keyframe_animation".split(","),function(a,g,e,c,b,d,i){function f(){var a=this._matrix,b=B(a.b,a.a),a=-B(a.c,a.d);return b>a?b:a}function k(a){var a=+a%(2*K)||0,b=this._matrix,c=b.tx,d=b.ty,f;f=b.deltaTransformPoint(this.origin);b.tx=-f.x;b.ty=-f.y;b.rotate(a-this.rotation);b.tx+=f.x+c;b.ty+=f.y+d}function n(){return this._matrix.clone()}function u(a){var b=this._matrix;b.a=a.a;b.b=a.b;b.c=a.c;b.d=a.d;b.tx=
a.tx;b.ty=a.ty}function q(){return this._matrix.tx}function t(a){this._matrix.tx=a}function p(){return this._matrix.ty}function m(a){this._matrix.ty=a}function o(){var a=this._matrix;return C(a.a*a.a+a.b*a.b)}function r(a){var b=this._matrix;if((a*=1)||0===a){var c=b.tx,d=this.scaleX,f=this.origin.x*d;b.tx=-f;b.scale(a/d,1);b.tx+=c+f}}function v(){var a=this._matrix;return C(a.d*a.d+a.c*a.c)}function w(a){var b=this._matrix;if((a*=1)||0===a){var c=b.ty,d=this.scaleY,f=this.origin.y*d;b.ty=-f;b.scale(1,
a/d);b.ty+=c+f}}function N(a){this.scaleX=this.scaleY=a}function J(a){this._opacity=1<a?1:0>a?0:+a}function O(){return this._origin.clone()}function G(a){var b=this._origin;b.x=a.x;b.y=a.y}function L(){Object.defineProperty(this,"id",{value:A++});this._attributes=Object.create(null,{_matrix:M(new c),matrix:j(n,u,!0),_opacity:M(1,!0),opacity:j(D,J,!0),_origin:M(new b),origin:j(O,G,!0),rotation:j(f,k,!0),scale:j(void 0,N),scaleX:j(o,r,!0),scaleY:j(v,w,!0),x:j(q,t,!0),y:j(p,m,!0)})}var j=g.descriptorAccessor,
M=g.descriptorData,s=g.getter,A=1,B=Math.atan2,C=Math.sqrt,K=Math.PI,D=s("_opacity"),s=L.prototype={parent:null,type:"DisplayObject",attr:function(a,b){var c,d,f=this._attributes;switch(arguments.length){case 0:c={};for(d in f)"_"!==d.charAt(0)&&(c[d]=f[d]);return c;case 1:if("string"===typeof a)return a in f&&"_"!==a.charAt(0)?f[a]:void 0;for(d in a)d in f&&"_"!==d.charAt(0)&&(f[d]=a[d]);this.markUpdate();return this;case 2:return a in f&&"_"!==a.charAt(0)&&(f[a]=b),this.markUpdate(),this}},destroy:function(){return this.removeAllListeners().remove()},
filters:function(){},mask:function(){},blendMode:function(){},markUpdate:function(){this.parent&&(e.needsDraw[this.id]=this)},remove:function(){var a=this.parent;a&&a.removeChild(this);return this},setOrigin:function(a,b){return this.attr("origin",{x:a,y:b})},composeRenderMessage:function(){var a={};a.attributes=this.attr();a.type=this.type;a.data=this._getRenderData();a.index=this.parent.getIndexOfChild(this);a.parentId=this.parent.id;return a},animate:function(a,b,c){var f=a;if(!(f instanceof d||
f instanceof i)){c||(c={});if(c.from&&!c.clock){for(f=this;!f.advance;f=f.parent);c.clock=f}f=new d(a,b,c)}f.play(this);return this},_getRenderData:function(){return null}};g.mixin(s,a);return L});define("movie",["./display_object","./display_list","./timeline","./tools"],function(a,g,e,c){function b(){a.call(this)}b.prototype=c.mixin(Object.create(a.prototype),e,g);return b});
define("shape",["./point","./segment_helper","./display_object","./tools"],function(a,g,e,c){function b(a){this._fill=v(a,this._fill)}function d(){return(this._fill&255)/255}function i(a){this._fill=(this._fill&4294967040|255*(1<a?1:0>a?0:a))>>>0}function f(a){this._line=v(a,this._line)}function k(a){if("butt"===a||"round"===a||"square"===a)this._cap=""+a}function n(a){if("miter"===a||"round"===a||"bevel"===a)this._join=""+a}function u(a){if(1<=a)this._miterLimit=+a}function q(){return(this._line&
255)/255}function t(a){this._line=(this._line&4294967040|255*(1<a?1:0>a?0:a))>>>0}var p,m=c.descriptorAccessor,o=c.descriptorData,r=c.getter,v=c.parseColor,w=g.validTokens,N=g.parsePath,J=g.exportToPath,O=g.parseCommandList,G=[].slice,L=Math.sin,j=Math.cos,M=Math.PI,s=2*M,A=r("_fill"),B=r("_line"),C=r("_cap"),K=r("_join"),D=r("_miterLimit");p=function(a){e.call(this);Object.defineProperties(this._attributes,{_cap:o("butt",!0),cap:m(C,k,!0),_fill:o(0,!0),fill:m(A,b,!0),fillOpacity:m(d,i,!0),_join:o("miter",
!0),join:m(K,n,!0),_line:o(255,!0),line:m(B,f,!0),lineOpacity:m(q,t,!0),lineWidth:o(0,!0,!0),_miterLimit:o(4,!0),miterLimit:m(D,u,!0)});this._segments=[];if("undefined"===typeof a)return this;var c=a instanceof Array?a[0]instanceof Array?a[0][0]:a[0]:a;if(-1!==w.indexOf(c))return this.segments.apply(this,arguments);if("number"===typeof c)return this.points.apply(this,arguments);if("string"===typeof a)return this.path(a);throw Error("Invalid parameter: "+a);};g=p.prototype=Object.create(e.prototype);
g.insertAt=function(){throw Error("not implemented");};g.segments=function(a){if("undefined"===typeof a)return this._segments.slice().map(function(a){return a.slice()});if(a instanceof Array)this._segments=a[0]instanceof Array?O(a.toString().split(",")):O(a);else if("string"===typeof a)this._segments=O.call(null,arguments);else throw Error("invalid parameter "+a);this.markUpdate();return this};g.points=function(a){if("undefined"===typeof a)return this._segments.map(function(a){return a.slice(-2)}).filter(Boolean);
for(var a=a instanceof Array?a:G.call(arguments),b=0,c,d,f=a.length;b<f;b+=2)c=a[b],d=a[b+1],0===b?this.clear().moveTo(c,d):this.lineTo(c,d);this.markUpdate();return this};g.path=function(a){var b=this._segments;if("undefined"===typeof a)return J(b);if("string"===typeof a)return b.push.apply(b,N(a)),this.markUpdate(),this;throw Error("invalid parameter "+a);};g.moveTo=function(a,b){this._segments.push(["moveTo",a,b]);this.markUpdate();return this};g.closePath=function(){this._segments.push(["closePath"]);
this.markUpdate();return this};g.lineTo=function(a,b){if("number"!==typeof a||"number"!==typeof b)throw Error("arguments are not valid. should be numbers. (x="+a+", y="+b+")");this._segments.push(["lineTo",a,b]);this.markUpdate();return this};g.lineBy=function(a,b){this._segments.push(["lineBy",a,b]);this.markUpdate();return this};g.verticalLineTo=function(a){return 0===this._segments.length?this.lineTo(0,a):this.lineTo(this.lastPoint()[0],a)};g.verticalLineBy=function(a){return this.lineBy(0,a)};
g.horizontalLineTo=function(a){if(0===this._segments.length)return this.lineTo(a,0);var b=this.lastPoint();return this.lineTo(a,b[1])};g.horizontalLineBy=function(a){return this.lineBy(a,0)};g.curveTo=function(a,b,c,d,f,e){if(0===this._segments.length)throw Error("You need at least a moveTo to add a curveTo.");if(6!==arguments.length)throw Error("curveTo: number of parameters is not valid.");this._segments.push(["curveTo",a,b,c,d,f,e]);this.markUpdate();return this};g.curveBy=function(){if(0===this._segments.length)throw Error("You need at least a moveTo to add a curveTo.");
if(6!==arguments.length)throw Error("curveTo: number of parameters is not valid.");this._segments.push(["curveBy",cp1x,cp1y,cp2x,cp2y,x,y]);this.markUpdate();return this};g.throughCurveTo=function(a,b,c,d){if(0===this._segments.length)throw Error("You need at least a moveTo to add a curveToThrough.");if(4!==arguments.length)throw Error("curveToThrough: number of parameters is not valid.");throw Error("not implemented");};g.arcTo=function(a,b,c,d,f,e,g){this._segments.push(["arcTo",a,b,c,d,f,e,g]);
this.markUpdate();return this};g.arcBy=function(a,b,c,d,f,e,g){this._segments.push(["arcBy",a,b,c,d,f,e,g]);this.markUpdate();return this};g.arc=function(a,b,c,d,f,e){0<this._segments.length&&this.lineTo(a,b);var g;g=e?f:d;e=e?s-d:f;f=e-g;if(Math.abs(f)>=s)return this.moveTo(a+c,b).arcTo(c,c,0,1,1,a+c*j(s),b+c*L(s)-1.0E-4);d=a+c*j(g);g=b+c*L(g);a+=c*j(e);b+=c*L(e);return this.moveTo(d,g).arcTo(c,c,0,f<M?0:1,1,a,b)};g.rect=function(a,b,c,d,f){if("undefined"!==typeof f)throw Error("radius not implemented");
return this.moveTo(a,b).lineBy(0,d).lineBy(c,0).lineBy(0,-d).closePath()};g.getBoundingBox=function(){throw"Not implemented";};g.pointAtLength=function(){throw"Not implemented";};g.pathLength=function(){throw Error("not implemented");};g.isPointInPath=function(){throw Error("not implemented");};g.pathReverse=function(){throw"Not implemented";};g.simplify=function(){throw Error("not implemented");};g.smooth=function(){throw Error("not implemented");};g.clear=function(){this._segments.length=0;return this};
g.morphTo=function(){throw Error("not implemented");};g.normalize=function(){throw Error("not implemented");};g.lastSegment=function(){var a=this._segments.slice(-1);if(0<a.length)return a;console.warn("No segments defined.")};g.lastPoint=function(){var a=this._segments.slice(-1)[0];if(1===a.length)for(var b,c=this._segments,d=c.length-1;0<d--;)if(b=c[d],"number"===typeof b[1])return[b[1],b[2]];return[a[1],a[2]]};g.type="Shape";g._getRenderData=function(){return this._segments.map(function(b){var c=
[];b.forEach(function(b,d){switch(!0){case 0===d:c.push(b);break;case b instanceof a:c.push([b.x,b.y]);break;default:c.push(b)}});return c})};p.arc=function(a,b,c,d,f,e){return(new p).arc(a,b,c,d,f,e)};p.circle=function(a,b,c){return(new p).arc(a,b,c,0,s)};p.rect=function(a,b,c,d,f){return(new p).rect(a,b,c,d,f)};return p});
define("bitmap",["./display_object","./asset_loading","./tools"],function(a,g,e){function c(c,e){a.call(this);this.source=c;this.type="bitmap";Object.defineProperties(this._attributes,{height:b(0,!0,!0),width:b(0,!0,!0)});this.load(c,"img");this.on("assetLoaded",function(a){debug("THE ASSET HAS BEEN LOADED",c,a.width+"x"+a.height);this.attr({width:a.width,height:a.height});e.call(this,this)})}var b=e.descriptorData;(c.prototype=e.mixin(Object.create(a.prototype),g)).composeRenderMessage=function(){var a=
{};a.attributes=this.attr();a.type=this.type;a.data={source:this.source};a.index=this.parent.getIndexOfChild(this);a.parentId=this.parent.id;return a};return c});
define("group",["./display_object","./display_list","./tools","./registry"],function(a,g,e,c){function b(){a.call(this);this._children=[]}var d=b.prototype=Object.create(a.prototype);e.mixin(d,g);d.markUpdate=function(){this.parent&&(c.needsDraw[this.id]=this,this._children.forEach(function(a){e.hitch(a,"markUpdate")()},this))};d.type="group";return b});
define("sprite",["./bitmap","./group","./asset_loading","./tools"],function(a,g,e,c){function b(a,b){g.call(this);this.sources=a;this.callback=b;this.currentBitmapIndex=0;Object.defineProperties(this._attributes,{height:d(0,!0,!0),width:d(0,!0,!0)});this._load()}var d=c.descriptorData,e=b.prototype=Object.create(g.prototype);e._load=function(){for(var b=this.sources,d=0,e=b.length;d<e;++d)new a(b[d],c.hitch(this,"_bitmapLoaded"))};e._bitmapLoaded=function(a){this.addChild(a);this._children.length===
this.sources.length&&this.callback.call(this,this._children)};e.composeRenderMessage=function(){var a={},b=this._children[this.currentBitmapIndex];this._children.forEach(function(a){a.type="bitmap_hidden"});a.attributes=this.attr();a.attributes.height=b.attr("height");a.attributes.width=b.attr("width");a.type="bitmap";a.data={source:b.source};a.index=this.parent.getIndexOfChild(this);a.parentId=this.parent.id;return a};return b});
define("bikeshed","./stage,./movie,./point,./shape,./bitmap,./group,./animation,./keyframe_animation,./easing,./matrix,./sprite".split(","),function(a,g,e,c,b,d,i,f,k,n,u){return{stage:a,Group:d,Movie:g,Point:e,Shape:c,Bitmap:b,Sprite:u,Animation:i,KeyframeAnimation:f,easing:k,Matrix:n}});
define("tree_helper",["./error","./tools"],function(a,g){var e=g.descriptorData,c=function(a){var b=a.parent;a===b.top&&(b.top=a.prev);a===b.bottom&&(b.bottom=a.next);a.next&&(a.next.prev=a.prev);a.prev&&(a.prev.next=a.next)},b=function(a,b,c){return Object.create(null,{id:e(a,!1,!1,!1),message:e(b,!0,!1,!1),parent:e(c,!0,!1,!1),next:e(null,!0,!1,!1),prev:e(null,!0,!1,!1)})};return{newTree:function(){return Object.create(null,{"0":e(b("ROOT",null),!0,!1,!1)})},newItem:b,insertAfter:function(a,b){if(a===
b)throw Error("insertItem mustn't be equal to afterItem.");if(!("parent"in a))throw Error("insertItem must have a parent property.");var f=a.parent;(b=b||f.top)?(c(a),b===f.top&&(f.top=a),b.next&&(b.next.prev=a),a.next=b.next,a.prev=b,b.next=a):(f.bottom=a,f.top=a)},tear:c}});
define("renderer",["./tree_helper","./tools","./event_emitter"],function(a,g,e){function c(){this._tree=d();this._waitingForParentId=null}var b=a.newItem,d=a.newTree,i=a.insertAfter,a=c.prototype={};a.stageController=null;a.render=function(a){if(!(a instanceof Array))throw Error("we only accept arrays atm.");var b=this;this._waitingForParentId=Object.create(null);this.clearStage();a.forEach(this.parseMessage,this);(function u(a){for(var c,d,f;null!==a;)c=a.message,d=a.id,f=a.parent,"bottom"in a&&
b.createGroup(d)&&u(a.bottom),c&&f&&b.drawItem(d,f.id,c),a=a.next;a&&a.prev&&u(a.prev.parent.next)})(this._tree[0])};a.parseMessage=function(a){var c=this._tree,d=this._waitingForParentId,e,g;e=a.parentId;if("undefined"===typeof e)throw Error("Mandatory property parentId is missing.");if(e in c){var t=a.id;if("undefined"===typeof t)throw Error("Mandatory property id is missing.");g=a.type;if("undefined"===typeof g)throw Error("Mandatory property type is missing.");if("undefined"===typeof("group"===
g))throw Error("Mandatory property isGroup is missing.");if("undefined"===typeof a.data)throw Error("Mandatory property data is missing.");g=c[e];(e=c[t])?e.message=a:(e=this._tree[t]=b(t,a,g),i(e));if("afterId"in a){c=c[a.afterId];if(!c)throw Error("afterId is unknown.");i(e,a.after)}t in d&&d[t].forEach(this.parseMessage,this);1===Object.keys(a).length&&this.removeObject(t)}else e in d?d[e].push(a):d[e]=[a]};a.drawItem=function(a,b,c){"Shape"===c.type&&this.drawShape(a,b,c.data,c.attributes);"bitmap"===
c.type&&this.drawBitmap(a,b,c.data,c.attributes)};g.mixin(c.prototype,e);return c});
define("raphael_renderer",["./renderer","./tools","./segment_helper"],function(a,g,e){var c=e.exportToPath,b={cap:"stroke-linecap",fill:"fill",fillOpacity:"fill-opacity",join:"stroke-linejoin",line:"stroke",lineWidth:"stroke-width",lineOpacity:"stroke-opacity",matrix:"transform",miterLimit:"stroke-miterlimit",opacity:"opacity",x:"x",y:"y"},d=function(a){var c,d={},e;for(e in a)switch(c=a[e],e){case "line":case "fill":d[b[e]]="rgba("+[c>>>24,c>>16&255,c>>8&255,c&255]+")";break;case "matrix":d[b[e]]=
Raphael.matrix(c.a,c.b,c.c,c.d,c.tx,c.ty).toTransformString();break;case "x":case "y":break;default:d[b[e]]=c}return d},e=function(b,c){a.call(this);this._stage=Raphael(b,c.width,c.height)},i=a.prototype,f=e.prototype=Object.create(i);f.render=function(a){i.render.call(this,a)};f.connectObject=function(a){a.click(g.hitch(this,function(b,c,d){this.emit("userevent",{id:a.id,type:"click",args:{x:c,y:d}})}));a.drag(g.hitch(this,function(b,c,d,e){this.emit("userevent",{id:a.id,type:"drag",args:{diffX:b,
diffY:c,x:d,y:e}})}))};f.drawShape=function(a,b,e,f){var b=this._stage,g=b.getById(a);if(null===g)g=b.path(""),g.id=a,this.connectObject(g);g.attr({path:"M0,0"+c(e)}).attr(d(f))};f.drawBitmap=function(a,b,c,e){b=this._stage;c=c.source;a=b.getById(a);a=b.image(c,0,0,e.width,e.height);a.attr(d(e))};f.createGroup=function(){return!0};f.clearStage=function(){this._stage.clear()};f.removeObject=function(a){a=this._stage.getById(a);if(null===a)throw Error("Unknown object.");a.remove()};f.changeOrder=function(){throw Error("not implemented");
};return e});
define("stage_controller",["./tools","./event_emitter","require"],function(a,g,e){function c(b,c,f){var g=new Worker(e.toUrl(f.workerScript));Object.defineProperties(this,{_worker:{value:g},_renderer:{value:b},_assetController:{value:c}});c.on("assetLoaded",a.hitch(this,function(a){this.post("assetLoaded",a)}));b.on("userevent",a.hitch(this,function(a){this.post("userevent",a)}));g.addEventListener("message",a.hitch(this,function(a){this.handleEvent(a)}));f.assets?c.preload(f.assets,function(){g.postMessage(f)}):
g.postMessage(f)}var b=c.prototype={handleEvent:function(a){a=a.data;switch(a.command){case "render":this.currentFrame=a.frame;this._renderer.render(a.data);break;case "play":case "stop":this.emit(a.command,a.data);break;case "debug":console.log.apply(console,["WORKER DEBUG:"].concat(a.data));break;case "loadAsset":this._assetController.load(a.data)}},play:function(a){return this.post("play",a)},post:function(a,b){this._worker.postMessage({command:a,data:b});return this},stop:function(a){return this.post("stop",
a)}};a.mixin(b,g);return c});define("extensions",{png:"img",jpg:"img",jpeg:"img",gif:"img",bmp:"img",svg:"img"});
define("asset_controller",["./extensions","./tools","./event_emitter"],function(a,g,e){function c(){this.assets={}}var b=c.handlers={img:function(a,b){var c=new Image;c.onload=function(){b(c,{width:c.width,height:c.height})};c.src=a;if(c.complete)c.onload(),c.onload=null}};c.prototype={load:function(a,c){var c=c||"assetLoaded",e=a.source,k=a.type;if(k in b)b[k](a.source,g.hitch(this,function(b,k){this.assets[e]=b;this.emit(c,g.mixin(a,k))}));else throw Error("Type not found in AssetController.handlers: "+
k);},preload:function(b,c){var b=b instanceof Array?b:[b],e=0,g,n,u=0,q=+new Date;this.on("_preloadedAssetLoaded",function(a){0===a.id.indexOf(q)&&u++;u===e&&c()});for(var t=0,p=b.length;t<p;++t)if(g=b[t],n=a[(g.match(/\.([a-z]+)$/i)||[,""])[1]])e++,this.load({source:g,type:n,id:q+"_"+t},"_preloadedAssetLoaded")}};g.mixin(c.prototype,e);return c});
define("main_controller",["./raphael_renderer","./stage_controller","./asset_controller"],function(a,g,e){return{_workerScript:"kernel.js",load:function(c,b,d){var i=document.createElement("a");i.href=b;d.url=i.href;d.framerate=d.framerate||60;d.workerScript=d.workerScript||this._workerScript;c=new a(c,d);b=new e;return new g(c,b,d)},loadFromScript:function(c,b,d){d.script=b;d.framerate=d.framerate||60;d.workerScript=d.workerScript||this._workerScript;c=new a(c,d);b=new e;return new g(c,b,d)},_setWorkerLocation:function(a){this._workerScript=
a}}});
if("undefined"!==typeof importScripts){var debug=function(){postMessage({command:"debug",data:[].slice.call(arguments)})};addEventListener("message",function init(g){var e=g.data;if(e.noCache)this.require={urlArgs:+new Date};e.requirePath&&importScripts(e.requirePath);removeEventListener("message",init);require(["bikeshed"],function(c){this.bikeshed=c;if(e.script){var b=c.stage;addEventListener("message",b);b.init(e);Function("stage",e.script)(b)}else{var d=new XMLHttpRequest;d.open("GET",e.url);d.send("");
d.onload=function(){d=null;var b=c.stage;addEventListener("message",b);b.init(e);Function("stage",this.responseText)(b)}}})})}else define("kernel",["./main_controller","./bikeshed"],function(a){window.bikeshed=a;for(var g="bikeshed.js",e=document.getElementsByTagName("script"),c=0,b=e.length;c<b;c++)if(e[c].src&&0<e[c].src.indexOf("bikeshed.js"))g=e[c].src;a._setWorkerLocation(g)});
