/**
  Copyright Joyent, Inc. and other Node contributors.
  Copyright 2011 uxebu Consulting Ltd. & Co. KG
  Copyright 2011 David Aurelio <aurelio@uxebu.com>

  Permission is hereby granted, free of charge, to any person obtaining a
  copy of this software and associated documentation files (the
  "Software"), to deal in the Software without restriction, including
  without limitation the rights to use, copy, modify, merge, publish,
  distribute, sublicense, and/or sell copies of the Software, and to permit
  persons to whom the Software is furnished to do so, subject to the
  following conditions:

  The above copyright notice and this permission notice shall be included
  in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
  NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
  DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
  OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
  USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
define("event_emitter",[],function(){var a;a={addListener:function(a,c){if("function"!==typeof c)throw Error("addListener only takes instances of Function");var e=this._events||(this._events=Object.create(null)),b=e[a],f,g;if(b){g=c.listener||c;for(e=0;f=b[e];e++)if(g===f||g===f.listener)return this;b.push(c)}else e[a]=[c];return this},emit:function(a,c,e){var b,f,g,h;g=this._events;if(a==="error"&&(!g||!g.error||!g.error.length))if(c instanceof Error)throw c;else throw Error("Uncaught, unspecified \u201cerror\u201d event.");
if(!g)return!1;if(g=g[a]){g=g.slice();f=arguments.length;switch(f){case 1:break;case 2:b=[c];break;case 3:b=[c,e];break;default:b=[];for(h=1;h<f;h++)b[h-1]=arguments[h]}for(h=0;f=g[h];h++)f.apply(this,b)}return this},listeners:function(a){var c=this._events||(this._events=Object.create(null));return c[a]||(c[a]=[])},once:function(a,c){if("function"!==typeof c)throw Error("once only takes instances of Function");var e=function(){this.removeListener(a,e);c.apply(this,arguments)};e.listener=c;return this.on(a,
e)},removeAllListeners:function(a){var c=this._events;arguments.length===0?delete this._events:c&&delete c[a];return this},removeListener:function(a,c){if("function"!==typeof c)throw Error("removeListener only takes instances of Function");var e,b,f=(e=this._events)&&e[a];if(e&&f)for(e=0;b=f[e];e++)if(c===b||c===b.listener){f.splice(e,1);break}return this}};a.on=a.addListener;return a});
define("color_map",{aliceblue:4042850303,antiquewhite:4209760255,aqua:16777215,aquamarine:2147472639,azure:4043309055,beige:4126530815,bisque:4293182719,black:255,blanchedalmond:4293643775,blue:65535,blueviolet:2318131967,brown:2771004159,burlywood:3736635391,cadetblue:1604231423,chartreuse:2147418367,chocolate:3530104575,coral:4286533887,cornflowerblue:1687547391,cornsilk:4294499583,crimson:3692313855,cyan:16777215,darkblue:35839,darkcyan:9145343,darkgoldenrod:3095792639,darkgray:2846468607,darkgreen:6553855,
darkgrey:2846468607,darkkhaki:3182914559,darkmagenta:2332068863,darkolivegreen:1433087999,darkorange:4287365375,darkorchid:2570243327,darkred:2332033279,darksalmon:3918953215,darkseagreen:2411499519,darkslateblue:1211993087,darkslategray:793726975,darkslategrey:793726975,darkturquoise:13554175,darkviolet:2483082239,deeppink:4279538687,deepskyblue:12582911,dimgray:1768516095,dimgrey:1768516095,dodgerblue:512819199,firebrick:2988581631,floralwhite:4294635775,forestgreen:579543807,fuchsia:4278255615,
gainsboro:3705462015,ghostwhite:4177068031,gold:4292280575,goldenrod:3668254975,gray:2155905279,green:8388863,greenyellow:2919182335,grey:2155905279,honeydew:4043305215,hotpink:4285117695,indianred:3445382399,indigo:1258324735,ivory:4294963455,khaki:4041641215,lavender:3873897215,lavenderblush:4293981695,lawngreen:2096890111,lemonchiffon:4294626815,lightblue:2916673279,lightcoral:4034953471,lightcyan:3774873599,lightgoldenrodyellow:4210742015,lightgray:3553874943,lightgreen:2431553791,lightgrey:3553874943,
lightpink:4290167295,lightsalmon:4288707327,lightseagreen:548580095,lightskyblue:2278488831,lightslategray:2005441023,lightslategrey:2005441023,lightsteelblue:2965692159,lightyellow:4294959359,lime:16711935,limegreen:852308735,linen:4210091775,magenta:4278255615,maroon:2147483903,mediumaquamarine:1724754687,mediumblue:52735,mediumorchid:3126187007,mediumpurple:2473647103,mediumseagreen:1018393087,mediumslateblue:2070474495,mediumspringgreen:16423679,mediumturquoise:1221709055,mediumvioletred:3340076543,
midnightblue:421097727,mintcream:4127193855,mistyrose:4293190143,moccasin:4293178879,navajowhite:4292783615,navy:33023,oldlace:4260751103,olive:2155872511,olivedrab:1804477439,orange:4289003775,orangered:4282712319,orchid:3664828159,palegoldenrod:4008225535,palegreen:2566625535,paleturquoise:2951671551,palevioletred:3681588223,papayawhip:4293907967,peachpuff:4292524543,peru:3448061951,pink:4290825215,plum:3718307327,powderblue:2967529215,purple:2147516671,red:4278190335,rosybrown:3163525119,royalblue:1097458175,
saddlebrown:2336560127,salmon:4202722047,sandybrown:4104413439,seagreen:780883967,seashell:4294307583,sienna:2689740287,silver:3233857791,skyblue:2278484991,slateblue:1784335871,slategray:1887473919,slategrey:1887473919,snow:4294638335,springgreen:16744447,steelblue:1182971135,tan:3535047935,teal:8421631,thistle:3636451583,tomato:4284696575,transparent:0,turquoise:1088475391,violet:4001558271,wheat:4125012991,white:4294967295,whitesmoke:4126537215,yellow:4294902015,yellowgreen:2597139199});
define("tools",["color_map"],function(a){function d(a,e,b){b=b<0?b+1:b>1?b-1:b;return b*6<1?a+(e-a)*b*6:b*2<1?e:b*3<2?a+(e-a)*(2/3-b)*6:a}return{descriptorAccessor:function(a,e,b,d){return{get:a,set:e,enumerable:!!b,configurable:!!d}},descriptorData:function(a,e,b,d){return{value:a,writable:!!e,enumerable:!!b,configurable:!!d}},getter:function(a){return function(){return this[a]}},mixin:function(a,e){var b,d,g,h,m=2,o=Object.keys;do if(e){h=o(e);b=0;for(d=h.length;b<d;b++)g=h[b],a[g]=e[g]}while(e=
arguments[m++]);return a},parseColor:function(c,e){var b,f;if(+c)return c>>>0;if(c in a)return a[c];if(/^#[0-9a-f]{6}$/i.test(c))return(parseInt(c.slice(1),16)<<8|255)>>>0;if(/^#[0-9a-f]{3}$/i.test(c)){c=parseInt(c.slice(1),16);f=c&3840;b=c&240;var g=c&15;return(f<<20|f<<16|b<<16|b<<12|g<<12|g<<8|255)>>>0}c=(""+c).split("(");if(c.length==2)switch(c[0]){case "rgb":b=/\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)$/,f=255;case "rgba":b||(b=/\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(0|1|[01]?(?:\.\d+))\s*\)$/);
if(b=b.exec(c[1]))return((b[1]&255)<<24|(b[2]&255)<<16|(b[3]&255)<<8|(f||b[4]*255&255))>>>0;break;case "hsl":b=/\s*(\d+)\s*,\s*(\d+)%\s*,\s*(\d+)%\s*\)$/,f=255;case "hsla":if(b||(b=/\s*(\d+)\s*,\s*(\d+)%\s*,\s*(\d+)%\s*,\s*(0|1|[01]?(?:\.\d+))\s*\)$/),b=b.exec(c[1])){var g=b[1]%360/360,h=b[2]/100,m=b[3]/100,h=m<=0.5?m*(h+1):m+h-m*h,o=m*2-h,m=d(o,h,g+1/3)*255,p=d(o,h,g)*255,g=d(o,h,g-1/3)*255;return((m+0.5<<16)+(p+0.5<<8)+(g+0.5|0)<<8|(f||b[4]*255&255))>>>0}}return e==null?255:e},hitch:function(a,
e){e||(e=a,a=null);if(typeof e=="string"){a=a||window;if(!a[e])throw["method not found"];return function(){return a[e].apply(a,arguments||[])}}return!a?e:function(){return e.apply(a,arguments||[])}},toArray:function(a,e,b){return(b||[]).concat(Array.prototype.slice.call(a,e||0))}}});
define("timeline",["event_emitter","tools"],function(a,d){var c=Math.round;return d.mixin({currentFrame:0,isPlaying:!0,advance:function(){var a=this.currentFrame;this.emit("advance",this,a);if(this.isPlaying)this.emit(a,this,a),this.currentFrame=(a+1)%this.length()||0},frames:function(a){var b,d,g=this.length(),h=0;for(d in a){if(d==+d)b=+d;else{b=+d.slice(0,-1);switch(d.slice(-1)){case "%":b=g*b/100;break;case "s":b*=60;break;default:throw Error("Unknown frame format: "+d);}b=c(b)}b>h&&(h=b);this.on(b,
a[d])}if(h>this._length)this._length=h+1;return this},length:function(a){var b=this._length||(this._length=0);if(arguments.length===0)return b;for(a*=1;b-- >=a;)this.removeAllListeners(b);this._length=a;return this},play:function(a){a*=1;this.isPlaying=!0;if(a>=0&&a<this.length())this.currentFrame=a,this.emit(a,this,a);return this},stop:function(a){a*=1;this.isPlaying=!1;if(a>=0&&a<this.length())this.currentFrame=a,this.emit(a,this,a);return this}},a)});
define("registry",[],function(){return{displayObjects:Object.create(null),movies:Object.create(null),needsDraw:Object.create(null)}});
define("display_list",["./registry"],function(a){var d;d={isVisible:!1,addChild:function(c,e){c.parent=this;c.isVisible=this.isVisible;a.displayObjects[c.id]=c;typeof c.advance==="function"&&(a.movies[c.id]=c);typeof e!=="undefined"?this._children.splice(e,0,c):this._children.push(c);this.isVisible&&c.markUpdate();return c},children:function(a){if(!a)return this._children.slice(0);a.forEach(function(a){this.add(a)},this);return this},clear:function(){this._children.slice(0).map(this.remove,this);
return this},getIndexOfChild:function(a){return this._children.indexOf(a)},removeChild:function(c){var e=this._children,b=e.indexOf(c);b!==-1&&(delete a.displayObjects[c.id],delete a.movies[c.id],delete a.needsDraw[c.id],e.splice(b,1));return this}};d.add=d.addChild;return d});
define("stage",["./event_emitter","./display_list","./timeline","./tools","./registry"],function(a,d,c,e,b){var f=b.movies,g={init:function(a){this.options=a;setInterval(g.loop,1E3/a.framerate)},handleEvent:function(a){if("message"===a.type)switch(a=message.command,a){case "play":case "stop":this[a](message.data)}},loop:function(){g.advance();for(var a in f)f[a].advance();var c=[],d;for(d in b.needsDraw){delete b.needsDraw[d];var p=b.displayObjects[d];a={id:d};if(p){if(!p.composeRenderMessage)continue;
e.mixin(a,p.composeRenderMessage())}c.push(a)}c.length&&postMessage({command:"render",data:c,frame:g.currentFrame})}};Object.defineProperty(g,"id",{value:0});e.mixin(g,a,d,c);g.isVisible=!0;g._children=[];return g});
define("point",[],function(){var a,d=Math.sqrt;a=function(a,b){this.x=a||0;this.y=b||0};var c=a.prototype=Object.create(null);c.add=function(a){this.x+=a.x;this.y+=a.y;return this};c.equals=function(a){return this.x===a.x&&this.y===a.y};c.clone=function(){return new a(this.x,this.y)};c.normalize=function(a){d(this.x*this.x+this.y*this.y);a/=this.length;this.x*=a;this.y*=a;return this};c.offset=function(a,b){this.x+=a;this.y+=b;return this};c.subtract=function(a){this.x-=a.x;this.y-=a.y;return this};
c.toString=function(){return this.x+","+this.y+" "};c.distance=function(a){var b=this.x-a.x,a=this.y-a.y;return d(b*b+a*a)};a.interpolate=function(c,b,d){return new a(c.x+d*(c.x-b.x),c.y+d*(c.y-b.y))};a.polar=function(c,b){return new a(c*Math.cos(b),c*Math.sin(b))};return a});define("error",[],function(){function a(a){this.name="ParserError";this.message=a[0]}a.prototype=Error();a.prototype.constructor=a;return{ParserError:a}});
define("segment_helper",["./point","./error"],function(a,d){function c(b,c){var h=[],g=!0,f=[],q,j,i,k,n,l,t,c=c||e;k=0;for(n=b.length;k<n;k++)if(i=b[k],g){h=[];if(!c[i])throw new d.ParserError(['Unknown command: "'+i+'"']);h.push(c[i].shorthands[0]);q=i;j=c[i].params.slice(0);(g=!j.length)&&f.push(h)}else{t=j.shift();switch(t){case "B":l=!!i;break;case "N":l=parseFloat(i,10);if(isNaN(l))throw new d.ParserError(['Invalid parameter for command "'+q+'", expected numeric but got "'+i+'".']);break;case "P":if(i instanceof
a)l=i;else{l=parseFloat(i,10);if(isNaN(l))throw new d.ParserError(['Could not create Point from String                   for command "'+q+'", expected numeric but got                   "'+i+'".']);i=parseFloat(b[++k],10);if(isNaN(i))throw new d.ParserError(['Could not create Point from String                    for command "'+q+'", expected numeric but got                    "'+b[k]+'".']);l=new a(l,i)}}h.push(l);j.length||(g=!0,f.push(h))}return f}var e={moveTo:{params:["P"],shorthands:["M"]},moveBy:{params:["P"],
shorthands:["m"]},closePath:{params:[],shorthands:["Z","z"]},lineTo:{params:["P"],shorthands:["L"]},lineBy:{params:["P"],shorthands:["l"]},verticalLineTo:{params:["N"],shorthands:["V"]},verticalLineBy:{params:["N"],shorthands:["v"]},horizontalLineTo:{params:["N"],shorthands:["H"]},horizontalLineBy:{params:["N"],shorthands:["h"]},svgArcTo:{params:["P","P","B","B","P"],shorthands:["A"]},svgArcBy:{params:["P","P","B","B","P"],shorthands:["a"]},canvasArcTo:{params:["P","P","N"],shorthands:["CA"]},bezierCurveTo:{params:["P",
"P"],shorthands:["C"]},bezierCurveBy:{params:["P","P"],shorthands:["c"]},curveTo:{params:["P","P","P"],shorthands:["C"]},curveBy:{params:["P","P","P"],shorthands:["c"]},throughCurveTo:{params:["P","P"],shorthands:["TC"]},throughCurveBy:{params:["P","P"],shorthands:["tc"]},quadraticCurveTo:{params:["P","P"],shorthands:["Q"]},quadraticCurveBy:{params:["P","P"],shorthands:["q"]},smoothBezierCurveTo:{params:["P","P"],shorthands:["S"]},smoothBezierCurveBy:{params:["P","P"],shorthands:["s"]},smoothCurveTo:{params:["P",
"P"],shorthands:["S"]},smoothCurveBy:{params:["P","P"],shorthands:["s"]},smoothQuadraticCurveTo:{params:["P"],shorthands:["T"]},smoothQuadraticCurveBy:{params:["P"],shorthands:["t"]}},b=[],f;for(f in e)b.push(f),b=b.concat(e[f].shorthands);var g={},h;for(h in e)g[e[h].shorthands[0]]={params:e[h].params,shorthands:e[h].shorthands[0]};return{commandMap:e,validTokens:b,parseCommandList:c,parseSvgPath:function(a){var b=[];a.replace(/([a-z])[\s,]*((-?\d*\.?\d*(?:e[\-+]?\d+)?\s*,?\s*)+)/ig,function(a,c,
h){b.push(c);h.replace(/(-?\d*\.?\d*(?:e[\-+]?\d+)?)\s*,?\s*/ig,function(a,c){c&&b.push(c)})});return c(b,g)}}});
define("easing",{linear:function(a){return a},quadIn:function(a){return Math.pow(a,2)},quadOut:function(a){return a*(a-2)*-1},quadInOut:function(a){a*=2;return a<1?Math.pow(a,2)/2:-1*(--a*(a-2)-1)/2},cubicIn:function(a){return Math.pow(a,3)},cubicOut:function(a){return Math.pow(a-1,3)+1},cubicInOut:function(a){a*=2;if(a<1)return Math.pow(a,3)/2;a-=2;return(Math.pow(a,3)+2)/2},quartIn:function(a){return Math.pow(a,4)},quartOut:function(a){return-1*(Math.pow(a-1,4)-1)},quartInOut:function(a){a*=2;if(a<
1)return Math.pow(a,4)/2;a-=2;return-0.5*(Math.pow(a,4)-2)},quintIn:function(a){return Math.pow(a,5)},quintOut:function(a){return Math.pow(a-1,5)+1},quintInOut:function(a){a*=2;if(a<1)return Math.pow(a,5)/2;a-=2;return(Math.pow(a,5)+2)/2},sineIn:function(a){return-1*Math.cos(a*(Math.PI/2))+1},sineOut:function(a){return Math.sin(a*(Math.PI/2))},sineInOut:function(a){return-1*(Math.cos(Math.PI*a)-1)/2},expoIn:function(a){return a==0?0:Math.pow(2,10*(a-1))},expoOut:function(a){return a==1?1:-1*Math.pow(2,
-10*a)+1},expoInOut:function(a){if(a==0)return 0;if(a==1)return 1;a*=2;if(a<1)return Math.pow(2,10*(a-1))/2;--a;return(-1*Math.pow(2,-10*a)+2)/2},circIn:function(a){return-1*(Math.sqrt(1-Math.pow(a,2))-1)},circOut:function(a){a-=1;return Math.sqrt(1-Math.pow(a,2))},circInOut:function(a){a*=2;if(a<1)return-0.5*(Math.sqrt(1-Math.pow(a,2))-1);a-=2;return 0.5*(Math.sqrt(1-Math.pow(a,2))+1)},backIn:function(a){return Math.pow(a,2)*(2.70158*a-1.70158)},backOut:function(a){a-=1;return Math.pow(a,2)*(2.70158*
a+1.70158)+1},backInOut:function(a){a*=2;if(a<1)return Math.pow(a,2)*(3.5949095*a-2.5949095)/2;a-=2;return(Math.pow(a,2)*(3.5949095*a+2.5949095)+2)/2},elasticIn:function(a){if(a==0||a==1)return a;a-=1;return-1*Math.pow(2,10*a)*Math.sin((a-0.075)*2*Math.PI/0.3)},elasticOut:function(a){return a==0||a==1?a:Math.pow(2,-10*a)*Math.sin((a-0.075)*2*Math.PI/0.3)+1},elasticInOut:function(a){if(a==0)return 0;a*=2;if(a==2)return 1;var d=0.3*1.5,c=d/4;if(a<1)return a-=1,-0.5*Math.pow(2,10*a)*Math.sin((a-c)*2*
Math.PI/d);a-=1;return 0.5*Math.pow(2,-10*a)*Math.sin((a-c)*2*Math.PI/d)+1},bounceIn:function(a){return 1-easingFuncs.bounceOut(1-a)},bounceOut:function(a){a<1/2.75?a=7.5625*Math.pow(a,2):a<2/2.75?(a-=1.5/2.75,a=7.5625*Math.pow(a,2)+0.75):a<2.5/2.75?(a-=2.25/2.75,a=7.5625*Math.pow(a,2)+0.9375):(a-=2.625/2.75,a=7.5625*Math.pow(a,2)+0.984375);return a},bounceInOut:function(a){return a<0.5?easingFuncs.bounceIn(a*2)/2:easingFuncs.bounceOut(a*2-1)/2+0.5}});
define("animation",["./easing","./timeline","./tools","./event_emitter"],function(a,d,c,e){function b(b,d){d=this.options=c.mixin({},f,d);this._parseEventProps();this.easingFunc=a[d.easing];this.framerate=d.framerate;this.duration=d.duration;this.frame=0;this.end=g(this.duration/1E3*this.framerate);this.timeline=d.timeline||this.makeTimeline();this.subjects=[];this.properties=b;this.propertyNames=Object.keys(this.properties);this.timeline.on("advance",c.hitch(this,"handleAdvance"))}var f=b.defaults=
{duration:1E3,easing:"linear",delay:0,framerate:30,getter:function(a){return this.object[a]},setter:function(a,b){return this.object[a]=b}},g=Math.floor;b.prototype={addSubject:function(a){if(!a.getter||!a.setter)a={object:a,getter:f.getter,setter:f.setter};this.subjects.push(a)},play:function(){this.frame===0&&this.begin();this.emit("play",this.subjects);this.isPlaying=!0},pause:function(){this.emit("pause",this.subjects);this.isPlaying=!1},begin:function(){this.emit("beforebegin",this.subjects);
var a=this;this.subjects.forEach(function(b){a.saveCurrentValues(b)});this.hasCustomTimeline&&this.timeline.start()},clone:function(){return new b(c.mixin({},this.properties),c.mixin({},this.options))},saveCurrentValues:function(a){a.initialValues={};for(var b in this.properties)a.initialValues[b]=a.getter(b)},handleAdvance:function(){this.isPlaying&&this.step()},_parseEventProps:function(){var a,b;for(a in this.options)a.indexOf("on")===0&&(b=a.substring(2).toLowerCase(),this.on(b,this.options[a]),
delete this.options[a])},reset:function(){this.frame=0;this.isPlaying=!1;this.hasCustomTimeline&&this.timeline.stop()},step:function(){++this.frame;for(var a=this.propertyNames,b=this.easingFunc,c=this.subjects,d,e,g=c.length,f=a.length,j,i,k,n=0;n<g;++n){e=b(this.frame/this.end);d=c[n];for(var l=0;l<f;++l)j=a[l],i=d.initialValues[j],k=this.properties[j],d.setter(j,i+(k-i)*e)}this.frame===this.end&&(this.emit("end",this.subjects),this.reset())},makeTimeline:function(){var a=c.mixin({},d),b=this.framerate,
e;this.hasCustomTimeline=!0;a.length(Infinity);a.stop=function(){clearInterval(e)};a.start=function(){e=setInterval(function(){a.advance()},1E3/b)};return a}};c.mixin(b.prototype,e);return b});
define("keyframe_animation",["./animation","./easing","./tools","./event_emitter"],function(a,d,c,e){function b(b,d){this.options=c.mixin({},a.defaults,d||{});this.duration=this.options.duration;this.framerate=this.options.framerate;this.animations=[];this.currentAnimation=-1;this.subjects=[];this.end=f(this.duration/1E3*this.framerate);this.keyframes=this._convertKeysToFrames(b);this.keys=Object.keys(this.keyframes).map(Number);this.keys.sort(function(a,b){return a-b});this._fillInProperties();this._createAnimations()}
var f=Math.floor,g={}.hasOwnProperty;b.prototype={addSubject:a.prototype.addSubject,play:function(){this.currentAnimation<0?this.begin():this.animations[this.currentAnimation].isPlaying=!0},pause:function(){if(this.currentAnimation>-1)this.animations[this.currentAnimation].isPlaying=!1},reset:function(){this.animations.forEach(function(a){a.reset()});this.currentAnimation=-1},begin:function(){var a=this.keyframes[0];a&&this.subjects.forEach(function(b){for(var c in a)b.setter(c,a[c])});this.currentAnimation=
0;this.animations[0].play()},_createAnimations:function(){var b,d=0,e,g=this.animations,f=this.keyframes;this.keys.forEach(c.hitch(this,function(s,q){var j;if(s!==0){b=s/this.end*this.duration-d;d+=b;j=new a(f[s],c.mixin(this.options,{duration:b}));j.subjects=this.subjects;if(e)e.on("end",c.hitch(this,function(){this.currentAnimation++;j.play()}));g.push(j);e=j;if(q===this.keys.length-1)j.on("end",c.hitch(this,function(){this.emit("end")}))}}))},_fillInProperties:function(){var a=this.end,b=this.keys,
c=this.keyframes,d,e={};b.forEach(function(a){d=c[a];for(var b in d)g.call(d,b)&&(e[b]=!0)});b.forEach(function(f,q){var j,i,k,n,l;d=c[f];for(l in e)if(!g.call(d,l)){a:{j=l;for(i=q;i--;)if(g.call(c[b[i]],j)){j=b[i];break a}j=null}a:{i=l;k=q;for(n=b.length;k<n;++k)if(g.call(c[b[k]],i)){i=b[k];break a}i=null}k=j&&c[j][l];n=i&&c[i][l];if(k==null)throw Error("No initial value specified for property: "+l);n==null&&(n=k,i=a);d[l]=n*(f-j)/(i-j)}})},_convertKeysToFrames:function(a){var b,d,a=c.mixin({},a);
for(b in a)if((d=this._convertKeyToFrame(b))!=null){if(d>this.end)this.end=d,this.duration=1E3*d/this.framerate;a[d]=c.mixin({},a[b]);d!==b&&delete a[b]}else delete a[b];return a},_convertKeyToFrame:function(a){var b;if(!isNaN(a))return a;b=(a.match(/\D+$/)||[])[0];a=parseFloat(a);switch(b){case "from":return 0;case "to":return this.end;case "s":return this.framerate*a;case "ms":return this.framerate*a/1E3;case "%":return this.end*a/100;default:return null}}};c.mixin(b.prototype,e);return b});
define("matrix",["point"],function(a){function d(a,c,d,e,m,o){this.a=a!=null?a:1;this.b=c||0;this.c=d||0;this.d=e!=null?e:1;this.tx=m||0;this.ty=o||0}var c=Math.cos,e=Math.sin;d.prototype={clone:function(){return new d(this.a,this.b,this.c,this.d,this.tx,this.ty)},concat:function(a){var c=this.a,d=this.b,e=this.c,m=this.d,o=this.tx,p=this.ty;this.a=c*a.a+d*a.c;this.b=c*a.b+d*a.d;this.c=e*a.a+m*a.c;this.d=e*a.b+m*a.d;this.tx=o*a.a+p*a.c+a.tx;this.ty=o*a.b+p*a.d+a.ty;return this},createBox:function(a,
c,d,e,m){return this.identify().rotate(d).scale(a,c).translate(e,m)},deltaTransformPoint:function(b){return new a(this.a*b.x+this.c*b.y,this.b*b.x+this.d*b.y)},identify:function(){this.a=this.d=1;this.b=this.c=this.tx=this.ty=0;return this},invert:function(){var a=this.a*this.d-this.b*this.c,c=this.a,d=this.b,e=this.c,m=this.d,o=this.tx,p=this.ty;this.a=m/a;this.b=-d/a;this.c=-e/a;this.d=c/a;this.tx=(e*p-m*o)/a;this.ty=(d*o-c*p)/a;return this},rotate:function(a){var f=c(a),a=e(a);return this.concat(new d(f,
a,-a,f,0,0))},scale:function(a,c){this.a*=a;this.b*=c;this.c*=a;this.d*=c;this.tx*=a;this.ty*=c;return this},transformPoint:function(b){return new a(this.a*b.x+this.c*b.y+this.tx,this.b*b.x+this.d*b.y+this.ty)},translate:function(a,c){this.tx+=a;this.ty+=c;return this}};return d});
define("display_object",["./event_emitter","./tools","./registry","./matrix","./animation","./keyframe_animation"],function(a,d,c,e,b,f){function g(){var a=this._matrix,b=v(a.b,a.a),a=-v(a.c,a.d);return b>a?b:a}function h(a){var a=+a%(2*u)||0,b=this._matrix,c=b.tx,d=b.ty;b.tx=b.ty=0;b.rotate(a-this.rotation);b.tx=c;b.ty=d}function m(){return this._matrix.clone()}function o(a){var b=this._matrix;b.a=a.a;b.b=a.b;b.c=a.c;b.d=a.d;b.tx=a.tx;b.ty=a.ty}function p(){return this._matrix.tx}function B(a){this._matrix.tx=
a}function s(){return this._matrix.ty}function q(a){this._matrix.ty=a}function j(){var a=this._matrix;return w(a.a*a.a+a.b*a.b)}function i(a){var b=this._matrix;a*=1;if(a||a===0){var c=b.tx,d=b.ty;b.tx=b.ty=0;a/=b.a*b.a+b.b*b.b;b.scale(a,1);b.tx=c;b.ty=d}}function k(){var a=this._matrix;return w(a.d*a.d+a.c*a.c)}function n(a){var b=this._matrix;a*=1;if(a||a===0){var c=b.tx,d=b.ty;b.tx=b.ty=0;a/=b.d*b.d+b.c*b.c;b.scale(1,a);b.tx=c;b.ty=d}}function l(a){this.scaleX=this.scaleY=a}function t(){Object.defineProperty(this,
"id",{value:z++});this._attributes=Object.create(null,{_matrix:C(new e),matrix:r(m,o,!0),rotation:r(g,h,!0),scale:r(void 0,l),scaleX:r(j,i,!0),scaleY:r(k,n,!0),x:r(p,B,!0),y:r(s,q,!0)})}var r=d.descriptorAccessor,C=d.descriptorData,z=1,v=Math.atan2,w=Math.sqrt,u=Math.PI,A=t.prototype={parent:null,type:"DisplayObject",attr:function(a,b){var c,d,e=this._attributes;switch(arguments.length){case 0:c={};for(d in e)d.charAt(0)!="_"&&(c[d]=e[d]);return c;case 1:if(typeof a=="string")return a in e&&a.charAt(0)!=
"_"?e[a]:void 0;for(d in a)d in e&&d.charAt(0)!="_"&&(e[d]=a[d]);this.markUpdate();return this;case 2:return a in e&&a.charAt(0)!="_"&&(e[a]=b),this.markUpdate(),this}},destroy:function(){return this.removeAllListeners().remove()},filters:function(){},mask:function(){},blendMode:function(){},markUpdate:function(){this.parent&&(c.needsDraw[this.id]=this)},remove:function(){var a=this.parent;a&&a.removeChild(this);return this},composeRenderMessage:function(){var a={};a.attributes=this.attributes();
a.type=this.type;a.data=this._getRenderData();a.index=this.parent.getIndexOfChild(this);a.parentId=this.parent.id;return a},animate:function(a,c){if(a instanceof b||a instanceof f)return a.addSubject({getter:d.hitch(this,"attr"),setter:d.hitch(this,"attr")}),a.play(),this;for(var e=this;!e.advance;e=e.parent);c||(c={});c.framerate=bikeshed.stage.options.framerate;c.timeline=e;return this.animate(new b(a,c))},_getRenderData:function(){return null}};A.attributes=A.attr;d.mixin(A,a);return t});
define("movie",["./display_object","./display_list","./timeline","./tools"],function(a,d,c,e){function b(){a.call(this)}b.prototype=e.mixin(Object.create(a.prototype),c,d);return b});
define("shape",["./point","./segment_helper","./display_object","./tools"],function(a,d,c,e){function b(a){this._fill=l(a,this._fill)}function f(){return(this._fill&255)/255}function g(a){this._fill=(this._fill&4294967040|(a>1?1:(a<0?0:a)*255))>>>0}function h(a){this._opacity=a>1?1:a<0?0:+a}function m(a){this._line=l(a,this._line)}function o(a){if(a=="butt"||a=="round"||a=="square")this._cap=""+a}function p(a){if(a=="miter"||a=="round"||a=="bevel")this._join=""+a}function B(a){if(a>=1)this._miterLimit=
+a}function s(){return(this._line&255)/255}function q(a){this._line=(this._line&4294967040|(a>1?1:(a<0?0:a)*255))>>>0}var j,i=e.descriptorAccessor,k=e.descriptorData,n=e.getter,l=e.parseColor,t=[].slice,r=Math.tan,C=Math.acos,z=Math.sin,v=Math.cos,w=Math.PI,u=w*2,A=d.validTokens,D=d.parseCommandList,E=d.parseSvgPath,F=n("_fill"),G=n("_opacity"),H=n("_line"),I=n("_cap"),J=n("_join"),K=n("_miterLimit");j=function(a){c.call(this);Object.defineProperties(this._attributes,{_cap:k("butt",!0),cap:i(I,o,
!0),_fill:k(0,!0),fill:i(F,b,!0),fillOpacity:i(f,g,!0),_join:k("miter",!0),join:i(J,p,!0),_line:k(255,!0),line:i(H,m,!0),lineOpacity:i(s,q,!0),lineWidth:k(0,!0,!0),_miterLimit:k(4,!0),miterLimit:i(K,B,!0),_opacity:k(1,!0),opacity:i(G,h,!0)});this._segments=[];return typeof a==="undefined"?this:this.add.apply(this,arguments)};d=j.prototype=Object.create(c.prototype);d.add=function(a){var b=a instanceof Array?a[0]:a;if(A.indexOf(b)!==-1)this.segments(t.call(arguments));else if(typeof b==="number")this.points.apply(this,
arguments);else if(typeof a==="string")this.svgPath(a);else throw Error("[Shape].add(param) expects a [WhatEver]. ");return this};d.insert=function(){throw Error("not implemented");};d.insertSegments=function(){throw Error("not implemented");};d.insertPoints=function(){throw Error("not implemented");};d.insertSvgPath=function(){throw Error("not implemented");};d.points=function(a){if(typeof a==="undefined")return this.segments.map(function(a){return a[0]}).filter(Boolean);else{var b,c,d,e;c=0;for(e=
arguments.length;c<e;c++)d=arguments[c],x=d[0],y=d[1],typeof x==="number"&&typeof y==="number"?this.lineTo(x,y):typeof d==="number"&&(b!=null?(this.lineTo(b,d),b=null):b=d);this.markUpdate()}return this};d.segments=function(a){var b=this._segments;if(typeof a==="undefined")return b.slice();else b.push.apply(b,D(arguments)),this.markUpdate();return this};d.svgPath=function(a){var b=this._segments;if(typeof a==="undefined")return b.map(function(a){return a.join("")}).join("");else b.push.apply(b,E(a)),
this.markUpdate();return this};d.svgArcTo=function(b,c,d,e,g,f,h){this._segments.push(["A",new a(b,c),d,e,g,new a(f,h)]);this.markUpdate();return this};j.svgArcBy=function(){throw"Not implemented";};d.moveTo=function(b,c){this._segments.push(["M",new a(b,c)]);this.markUpdate();return this};d.closePath=function(){this._segments.push(["Z"]);this.markUpdate();return this};d.lineTo=function(b,c){if(typeof b!=="number"||typeof c!=="number")throw Error("arguments are not valid. should be numbers.");this._segments.push(["L",
new a(b,c)]);this.markUpdate();return this};d.lineBy=function(b,c){if(typeof b!=="number"||typeof c!=="number")throw Error("arguments are not valid. should be numbers.");this._segments.push(["l",new a(b,c)]);this.markUpdate();return this};d.verticalLineTo=function(a){if(this._segments.length===0)return this.lineTo(0,a);else if(typeof a==="number")return this.lineTo(this.lastPoint().x,a);else throw Error("number of parameters is not valid.");};d.verticalLineBy=function(a){if(typeof a==="number")return this.lineBy(0,
a);else throw Error("number of parameters is not valid.");};d.horizontalLineTo=function(a){if(typeof a==="number")if(this._segments.length===0)return this.lineTo(a,0);else{var b=this.lastPoint();return this.lineTo(a,b.y)}else throw Error("number of parameters is not valid.");};d.horizontalLineBy=function(a){if(this._segments.length===0||typeof a==="number")return this.lineBy(a,0);else throw Error("number of parameters is not valid.");};d.bezierCurveTo=function(b,c,d,e,g,f){if(this._segments.length===
0)throw Error("You need at least a moveTo to add a bezierCurveTo.");else if(arguments.length!==6)throw Error("bezierCurveTo: number of parameters is not valid.");this._segments.push(["C",new a(g,f),new a(b,c),new a(d,e)]);this.markUpdate();return this};d.throughCurveTo=function(a,b,c,d){if(this._segments.length===0)throw Error("You need at least a moveTo to add a curveToThrough.");else if(arguments.length!==4)throw Error("curveToThrough: number of parameters is not valid.");throw Error("not implemented");
};d.curveTo=function(){return this.bezierCurveTo.apply(this,arguments)};d.curveBy=function(){return this.bezierCurveBy.apply(this,arguments)};d.arc=function(a,b,c,d,e,g){this._segments.length>0&&this.lineTo(a,b);var f;f=g?e:d;g=g?u-d:e;e=g-f;if(Math.abs(e)>=u)return this.moveTo(a+c,b).svgArcTo(c,c,0,1,1,a+c*v(u),b+c*z(u)-1.0E-4);d=a+c*v(f);f=b+c*z(f);a+=c*v(g);b+=c*z(g);return this.moveTo(d,f).svgArcTo(c,c,0,e<w?0:1,1,a,b)};d.canvasArcTo=function(b,c,d,e,g){if(typeof b!=="number"||typeof c!=="number"||
typeof d!=="number"||typeof e!=="number"||typeof g!=="number")throw Error("one or more parameters are not numbers.");var b=new a(b,c),f=new a(d,e);if(this._segments.length===0)throw Error("arcTo needs a valid subpath.");e=this.lastPoint();if(e.equals(b)||b.equals(f)||g===0)return this.lineTo(b.x,b.y);if(e.x===b.x===f.x||e.y===b.y===f.y)return this.lineTo(b.x,b.y);var c=e.distance(b),d=f.distance(b),e=e.clone().subtract(b),f=f.clone().subtract(b),h=g*r(C(-(e.x*f.x+e.y*f.y)/(c*d))/2),c=new a(b.x+h*
e.x/c,b.y+h*e.y/c),b=new a(b.x+h*f.x/d,b.y+h*f.y/d),d=e.x*f.y-e.y*f.x>0?"0":"1";return this.lineTo(c.x,c.y).svgArcTo(g,g,0,0,d,b.x,b.y)};d.rect=function(a,b,c,d,e){if(typeof e!=="undefined")throw Error("radius not implemented");else return this.moveTo(a,b).verticalLineBy(d).horizontalLineBy(c).verticalLineBy(-d).closePath()};d.getBoundingBox=function(){throw"Not implemented";};d.pointAtLength=function(){throw"Not implemented";};d.pathLength=function(){return 3};d.isPointInPath=function(){throw Error("not implemented");
};d.pathReverse=function(){throw"Not implemented";};d.simplify=function(){throw Error("not implemented");};d.smooth=function(){throw Error("not implemented");};d.clear=function(){this._segments.length=0};d.morphTo=function(){throw Error("not implemented");};d.normalize=function(){throw Error("not implemented");};d.lastSegment=function(){var a=this._segments.slice(-1);if(a.length>0)return a;else console.warn("No segments defined.")};d.lastPoint=function(){var a=this._segments.slice(-1)[0][1];if(typeof a===
"undefined")for(var b=this._segments,c=b.length-1;c-- >0;)b[c][0]==="M"&&(a=b[c][1]);return a};d.type="Shape";d._getRenderData=function(){return this._segments.map(function(b){var c=[];b.forEach(function(b,d){switch(!0){case d===0:c.push(b);break;case b instanceof a:c.push([b.x,b.y]);break;default:c.push(b)}});return c})};j.arc=function(a,b,c,d,e,f){return(new j).arc(a,b,c,d,e,f)};j.circle=function(a,b,c){return(new j).arc(a,b,c,0,u)};j.rect=function(a,b,c,d,e){return(new j).rect(a,b,c,d,e)};return j});
define("group",["./display_object","./display_list","./tools","./registry"],function(a,d,c,e){function b(){a.call(this);this._children=[]}var f=b.prototype=Object.create(a.prototype);c.mixin(f,d);f.markUpdate=function(){this.parent&&(e.needsDraw[this.id]=this,this._children.forEach(function(a){c.hitch(a,"markUpdate")()},this))};f.type="group";return b});
define("bikeshed",["./stage","./movie","./point","./shape","./group","./animation","./keyframe_animation","./easing","./matrix"],function(a,d,c,e,b,f,g,h,m){return{stage:a,Group:b,Movie:d,Point:c,Shape:e,Animation:f,KeyframeAnimation:g,easing:h,Matrix:m}});
